### ISSUE TITLE
Plugin should be enabled for each project separately

### ISSUE THREAD

**Issue by dubreuia** [dubreuia/intellij-plugin-save-actions#10]
From the plugin page comment section:

andyrozman 
2015-05-04 11:34:21
Great plugin... Just something I wanted when I switched from Eclipse... While it's great, there is one thing missing... Plugin should be enabled for each project separately... I am using my IntelliJ for two different project, I need Save actions for one of them but not for the other one...

**Comment by dubreuia** [comment]
Should migrate to new storage api: http://www.jetbrains.org/intellij/sdk/docs/basics/persisting_state_of_components.html

**Comment by dubreuia** [comment]
Also use `projectConfigurable` instead of `applicationConfigurable` in plugin.xml

**Comment by atsu85** [comment]
I'd also like to be able to enable/disable this plugin for specific projects

**Comment by goerge** [comment]
+1

**Comment by markiewb** [comment]
PR for this issue https://github.com/dubreuia/intellij-plugin-save-actions/pull/68

**Comment by dubreuia** [comment]
Merged v0.14
