### ISSUE TITLE
Reformat only changed code

### ISSUE THREAD

**Issue by bikerp** [dubreuia/intellij-plugin-save-actions#100]
Hi,
I'm facing an issue with reformating the code. Although I have git properly configured in IntelliJ (2017.2.2) the whole file is affected even though I change only one line. 
Thanks in advance for the fix.
Pavel

**Comment by bikerp** [comment]
It's duplicate of issue #35. So you may close it.

**Comment by dubreuia** [comment]
Hey @bikerp, no actually #35 is for inspections (the quick fix section in the settings). The option "Reformat only changed code" should apply on changed lines, the quick fix on the whole file.

**Comment by bikerp** [comment]
Hi @dubreuia, I thougt that the reformat feature also includes inspections. And my comment was concerning inspections (particulary adding final to method parameters). Lately I found the #35 and figured out that inspections change whole file. So I'm sorry for confusion.
