### ISSUE TITLE
Color scheme breaks after save

### ISSUE THREAD

**Issue by JacopoGobbi** [dubreuia/intellij-plugin-save-actions#101]
when saving, the main method got moved from bottom to the top of the class (there are other method in the class), this caused the color scheme to break.

![screenshot from 2017-08-29 14-01-52](https://user-images.githubusercontent.com/11658632/29822271-c87c637e-8cc2-11e7-98a1-b41c08408273.png)

**Comment by JacopoGobbi** [comment]
it actually messed up a lot of things so that I had to reload the project:
1) One class reference was not being found
2) Ctrl+Click was highlighting in the wrong place

**Comment by markiewb** [comment]
I guess you had compile errors or you haven't been done typing. Invoking
the save actions on an incomplete file can lead to such issues you
described.

 Enable the option "no action if compile errors"

Den 29 aug. 2017 3:08 em skrev "Jacopo Gobbi" <notifications@github.com>:

**Comment by dubreuia** [comment]
@JacopoGobbi What other plugins are you using? Basically if the save-actions triggers while you are still typing / viewing the code, it's because another plugin is forcing file write more often than it should.

**Comment by JacopoGobbi** [comment]
@dubreuia 
![screenshot from 2017-09-01 17-58-38](https://user-images.githubusercontent.com/11658632/29979904-3bf998c0-8f3f-11e7-8398-1ab799087435.png)
Nothing too weird :/ I think maybe I could have compile errors as @markiewb described, I will update you on this now that finally #53 seems to be fixed :)

**Comment by dubreuia** [comment]
@JacopoGobbi Can you post IDE info please?

**Comment by JacopoGobbi** [comment]
IntelliJ IDEA 2017.2.2
Build #IU-172.3757.52, built on August 15, 2017
JRE: 1.8.0_152-release-915-b10 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.10.0-33-generic
I'm using Ubuntu Gnome 17.04
