### ISSUE TITLE
Changing pom.xml (Maven) leads to nonparseable pom

### ISSUE THREAD

**Issue by bartmark** [dubreuia/intellij-plugin-save-actions#102]
If i change something in a pom.xml the auto save actions lead to corrupting the xml document.
This element &lt;project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"&gt;
is broken after saving with save actions plugin and leads to 
<project a-instance" xmlns="http://maven.apache.org/POM/4.0.0"mxmlns:xsi="http://www.w3.org/2001/XMLSche
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
Please fix this soon, due to this is very annoying

**Comment by dubreuia** [comment]
Hello @bartmark. I can't reproduce: can you post intellij version and any non-jetbrains plugins you have installed (like formatters), they tend to interact badly with save-actions.

**Comment by dubreuia** [comment]
You can also exclude pom files from save-actions, in "Settings > Other > Save actions > Exclusions > +" then add an exclusion with pattern "pom.xml" (without the quotes)
