### ISSUE TITLE
File type exclusion

### ISSUE THREAD

**Issue by Nedorot** [dubreuia/intellij-plugin-save-actions#111]
Would it be possible to make it easier to exclude file-types ?
- Currently, the popup indicates the wrong regexp (.\*\\.properties instead of .\*/.\*\\.properties)
- It would be nice to be able to add a file extension without the whole regex...

Thanks for a great plugin !!!

**Comment by dubreuia** [comment]
Hey @Nedorot, I already have a lot of features to implement and this is already supported so I won't implement it. I can correct the regex in the popup though.

You can send a PR for the feature, I'll close this one when I correct the regex.

**Comment by dubreuia** [comment]
WNF
