### ISSUE TITLE
Braces on single statement blocks

### ISSUE THREAD

**Issue by MartinX3** [dubreuia/intellij-plugin-save-actions#117]
Could there be an option, that removes braces from single statement if(), for() and so on?
Save Action places them at every for(), if(), etc, but in my company we use a refactoring book from martin fowler, which says, that you never ever put braces at a single statement block.

**Comment by dubreuia** [comment]
No problem to add that quick fix, you do a PR anytime. Thanks

**Comment by MartinX3** [comment]
Thank you.

I advertise your plugin, where I can
