### ISSUE TITLE
Add multiple projects selection for configuration

### ISSUE THREAD

**Issue by dubreuia** [dubreuia/intellij-plugin-save-actions#120]
> Could you please add the possibility to select multiple projects that plugin will interact with? It's annoying that I have to select checkboxes in every new project I create (https://plugins.jetbrains.com/plugin/7642-save-actions#comment=24764)

**Comment by dubreuia** [comment]
This is the opposite of #10 (maybe add an option "apply to all projects")

**Comment by dubreuia** [comment]
Related to #137

**Comment by smartwjw** [comment]
Please make this an option, we really need it, @dubreuia .

**Comment by dubreuia** [comment]
Hey @smartwjw, I won't have time anytime soon, but you can always submit a PR for it. Thanks.
