### ISSUE TITLE
Add quick fix to kotlin language

### ISSUE THREAD

**Issue by tspoke** [dubreuia/intellij-plugin-save-actions#122]
I use this plugin on all my projects and I like it a lot. I recently started a project in Kotlin and your plugin seems to not support it yet. 

I would love to see a Kotlin support for this plugin. Any plan for this ?

Thank you.

**Comment by dubreuia** [comment]
Hey @tspoke thank you for your interest in the plugin. 

Kotlin is gaining speed right now, it's important that save-actions works for it. I'll check it out. 

What IDE are you using? Intellij IDEA? IFAIK there's no dedicated Jetbrains IDE for Kotlin

**Comment by tspoke** [comment]
Hi @dubreuia, thank you for your interest to this issue.

I'm using Android Studio, it's the intellij's Google version for Android dev. They support kotlin/java in the IDE natively (since v3).

**Comment by markiewb** [comment]
@tspoke: What part of the plugin does not work? What exactly do you miss?

I tested it and the basic actions work. I created a kotlin/jvm project in IDEA, configured the Save actions plugin and the optimize imports and format actions where invoked while saving

**Comment by tspoke** [comment]
My code is not formatted at all on my side with Android Studio IDE. Curly braces are not added to simple if/else. Spaces are not added. Looks like *.kt files are not processed.

Did I miss something ? Thanks

**Comment by dubreuia** [comment]
> Curly braces are not added to simple if/else 
That's is Java only (for now) but the rest (reformat, spaces, etc.) should work for any langages. 

@markiewb I think it is specific to Android Studio, looks like it works in IDEA

**Comment by SharpMobileCode** [comment]
+1 for including "Kotlin inspection and quick fix" support as well.  Very nice plugin!

**Comment by dubreuia** [comment]
Glad you appreciate the plugin @SharpMobileCode 

I'd really like to add quick fix support to Kotlin, but I don't see myself having time for that anytime soon. The dev time is pretty substantial: add kotlin language detection (like java), write a kotlin processor, find kotlin quickfixes (those probably needs to be written, for java they are already in jetbrains code, I'm just calling them). A pull request for this would be really appreciated.

Like @markiewb said, basic actions like reformat and imports should work.

**Comment by dubreuia** [comment]
Move to https://github.com/dubreuia/intellij-plugin-save-actions/projects/2 (ideas)
