### ISSUE TITLE
The settings panel alignment is off

### ISSUE THREAD

**Issue by dubreuia** [dubreuia/intellij-plugin-save-actions#129]

**Comment by markiewb** [comment]
Can you please post a screenshot!

**Comment by dubreuia** [comment]
In red in the screenshot. I don't understand how panel panel placement works in swing, I took took me way too much time to do this and it's still not aligned.

Also I'm unable to set a fixed width for the `FileMaskPanel` and `IdeSupportPanel` (the last two) so their size is defined by their content and it annoys me.

![settings-panel-not-left-aligned](https://user-images.githubusercontent.com/657731/33231932-d24acd48-d1fd-11e7-9799-15666ca40a3b.png)
