### ISSUE TITLE
Reformat only changed code 

### ISSUE THREAD

**Issue by jiqimaogou** [dubreuia/intellij-plugin-save-actions#130]
Reformat only changed code  somethings reformat the entire file.

**Comment by dubreuia** [comment]
I need more info:

- Do you have a VCS configured in Intellij? (if not, the option will always reformat on whole file) 
- What version of intellij and the plugin are you using?
- What do you mean by "somethings"? Sometimes? What times exactly?

Thanks

**Comment by hosswald** [comment]
Duplicate of #114.

**Comment by MicNeo** [comment]
Hi,

I have same problem, I've checked option to format only code changed by me, but e.g. it adds final keywords to vars in methods I haven't touched. I use git, and it works as expected. Do I need setup VCS somehow special to get it working with this plugin?

My Intellij version: 2017.2.2, plugin: 0.25
