### ISSUE TITLE
Performance and feedback issue on big refactorings

### ISSUE THREAD

**Issue by dubreuia** [dubreuia/intellij-plugin-save-actions#132]
I have two issues with save-actions when refactoring code (500+ modified files)

- *performance*: the save-actions are applied individually for each files (that means potentially a new thread is started for each file / action)
- *feedback*: there is no UI feedback that something is happening (there should be some kind of progress bar)

It might means save-actions will need to have two modes: "normal" mode and "batch" mode. In batch mode, it should just list the files that needs action, then spawn one thread for all.

**Comment by egmanoj** [comment]
I'd like to run Save Actions in "batch mode" for a directory/set of directories.

**Comment by dubreuia** [comment]
Fixed by #169 .
