### ISSUE TITLE
[Java inspection] Add quick fix "tighten access inspection"

### ISSUE THREAD

**Issue by dubreuia** [dubreuia/intellij-plugin-save-actions#135]
Submitted by email

> Is it possible to somehow configure it to fix the 'Access can be package-private' warning automatically
> I haven't found a way to have package-private access by default...

It seems the inspection is already in intellij code, `AccessCanBeTightenedInspection`, adding it to `InspectionFactory` and in the settings panel should do the job.

I won't have time to do the dev, but a PR can be submitted anytime

**Comment by rw00** [comment]
I'll try to do this by tomorrow

**Comment by rw00** [comment]
For some reason `AccessCanBeTightenedInspection` is not a public class. Might need a bit more investigation on how to workaround this

**Comment by dubreuia** [comment]
@rw00 It's package-private, extend it in the same package and you'll have access. If it's not enough, I don't mind copy pasting the class in the plugin (that part of JetBrain's code is really not usable / extensible).

**Comment by dubreuia** [comment]
I'm adding this to next version

**Comment by dubreuia** [comment]
Hey @rw00 I'm about to release the plugin with your 2 other PR, do you want this issue to be part of the release too?

**Comment by rw00** [comment]
Hey @dubreuia
I was able to add this inspectionTool like you described but it just didn't do any fixes when I ran it. 
I will have to debug to know why it didn't work.

**Comment by dubreuia** [comment]
Ok keep me posted if you find anything. Thanks
