### ISSUE TITLE
Final line feed removed

### ISSUE THREAD

**Issue by quilicicf** [dubreuia/intellij-plugin-save-actions#139]
Hi, 

We've noticed recently with a colleague that save actions was removing the line feed at the end of files. 
Problem is, the POSIX definition of a line states that it should end with a line feed. When this is not the case some scripts can't read the last line of a file (happened to us with shell scripts for example).

We've added a rule in our team to check the `ensure line feed` option of intelliJ when working on our repos.

We are using save actions version `0.24` which I think is the last version. 

My intelliJ:

```
IntelliJ IDEA 2017.3.1 (Ultimate Edition)
Build #IU-173.3942.27, built on December 11, 2017
Licensed to Cyprien Quilici
JRE: 1.8.0_152-release-1024-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.4.0-104-generic
```

I've looked at the recent commits on this repo but I can't find something odd. 
I updated IntelliJ and save actions at the same time so I don't know if it's an IntelliJ or save actions issue. 
I'm out of clues to go further :-(

**Comment by dubreuia** [comment]
it's a config in intellij, make you have this option ticked.

![screenshot from 2018-01-06 14-14-13](https://user-images.githubusercontent.com/657731/34643081-06c037d4-f2ec-11e7-8d25-4c1388837bf6.png)

I'll close this issue if this works out for you.

**Comment by quilicicf** [comment]
Well it seems the problem was with intelliJ. The checkbox was ticked but save actions was still removing the last line feed. 
After the last upgrade of IntelliJ I can't reproduce anymore. 
I'll try with my colleague's computer then close if we can't reproduce.
Thanks for the reply anyway :)

**Comment by quilicicf** [comment]
It looks like it was indeed an IntelliJ issue. 
It is fixed on my colleague's side too. 
Sorry for the inconvenience.
