### ISSUE TITLE
Add missing @Override broken after IntelliJ 2017.3.2 update on jdk inherited methods

### ISSUE THREAD

**Issue by nikowitt** [dubreuia/intellij-plugin-save-actions#140]
Hi there,

using Save Actions 0.24 after the latest IntelliJ update seems to somehow render "Add missing @Override" to do nothing. Other features like reformat code still seem to work.

IntelliJ IDEA 2017.3.2 (Community Edition)
Build #IC-173.4127.27, built on December 25, 2017
JRE: 1.8.0_152-release-1024-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.11.2-041102-generic

Can this be confirmed by somebody else?

*UPDATE: it seems that this is not a generic issue, but seems to happen on toString() methods only.*

Thanks in advance!
Regards,
Niko

**Comment by dubreuia** [comment]
Yeah it seems it doesn't work anymore on `toString`, `hashCode`, etc. The quick fix "Annotate method with @Override" is not available anymore on those methods, and the save-actions plugin needs this to work.

Can you open a bug at Jetbrains with the above description please? At https://youtrack.jetbrains.com/

**Comment by nikowitt** [comment]
Created
https://youtrack.jetbrains.com/issue/IDEA-184671.

**Comment by markiewb** [comment]
See the comment at https://youtrack.jetbrains.com/issue/IDEA-184671
It is just a setting. Perhaps the default value has changed?

**Comment by dubreuia** [comment]
I'm testing this today

**Comment by dubreuia** [comment]
v0.25

**Comment by nikowitt** [comment]
Works fine, thanks for the quick response!
