### ISSUE TITLE
Java inspection and quick fixes only form formatted code

### ISSUE THREAD

**Issue by MicNeo** [dubreuia/intellij-plugin-save-actions#142]
Would it be possible to run quick fixes only for changed code? e.g. I add new method, and I use final keywords for my variables, I want to added them automatically, but I don't want to do that for whole class.

**Comment by dubreuia** [comment]
Hey @MicNeo. That would be great! You can submit a PR anytime to support that. Thanks.

**Comment by dubreuia** [comment]
Check out https://github.com/dubreuia/intellij-plugin-save-actions#contributing and I'm available for help if needed.

**Comment by dubreuia** [comment]
Duplicates #35
