### ISSUE TITLE
"Reformat only changed code" is not respected by "Add final to field/local variable"

### ISSUE THREAD

**Issue by pascalschumann** [dubreuia/intellij-plugin-save-actions#143]
Steps to reproduce:
1. Enable the Options:
"Reformat only changed code (only if VCS configured)"
"Add final to field"
"Add final to local variable"
2. change code in one file that is tracked by git.
3. save and you will see, it add final flags to untouched lines.

**Comment by dubreuia** [comment]
Hey @pascalschumann. Thanks for the issue! This is not implemented but you can submit a PR anytime if you want to add it. Check out https://github.com/dubreuia/intellij-plugin-save-actions#contributing

**Comment by dubreuia** [comment]
Duplicates #35
