### ISSUE TITLE
Build multi release binary

### ISSUE THREAD

**Issue by dubreuia** [dubreuia/intellij-plugin-save-actions#145]
Only if it doesn't prevent users to use the plugin

**Comment by dubreuia** [comment]
Regarding https://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/build_number_ranges.html and the pricing in https://www.jetbrains.com/idea/buy/#edition=personal, I can update the SDK to 2016.3 without fear of losing users, since they can all upgrade to the latest of 2016 with their perpetual fallback licenses (we're already on 2016.3).

Then I can update to 2017.3, and provide a jar for 2016 users (and so on for 2018 version in a next issue).

**Comment by dubreuia** [comment]
https://github.com/JetBrains/intellij-plugin-verifier

**Comment by dubreuia** [comment]
It might work without providing a binary for each specific intellij version, need to check with https://github.com/JetBrains/intellij-plugin-verifier. 

If it doesn't work, we can provide multiple builds like:

- [145.0, 163.*] : SDK 2016.3 (this is current build) for IDEA 2016.1 through 2016.3.X.
- [171.1, 173.*] : SDK 2017.3 for IDEA 2017.1 through IDEA 2017.3.X
- [181.1, 185.*] : SDK 2018.? for IDEA 2018.1 to now

**Comment by dubreuia** [comment]
https://github.com/JetBrains/intellij-scala does it too

**Comment by dubreuia** [comment]
Don't need this for now.

**Comment by dubreuia** [comment]
We need this

**Comment by dubreuia** [comment]
TODO:

- Create 2 version branches from master: 2018.x and 2016.x
    - Branch 2016.x: `ideaVersion=2016.3` and `<idea-version since-build="163.0" until-build="191.0"/>` (verify)
    - Branch 2018.x: `ideaVersion=2018.1` and `<idea-version since-build="191.0"/>` (verify)
- Code is merged in master, then reported by hand in version branches if necessary
- Code isn't released from master anymore, only from version branch (update release script to append idea version to release version)
- Bonus: release from travis https://docs.travis-ci.com/user/deployment/releases/

**Comment by dubreuia** [comment]
- Branch `master` with no version / tags
- Branch `idea-version-2016` : tags as `1.5.0-2016` for version 1.5.0 (with corresponding release)
- Branch `idea-version-2018` : tags as `1.5.0-2018` for version 1.5.0 (with corresponding release)
- Milestone `1.5.0-2016` (multiple milestone possible?)

**Comment by dubreuia** [comment]
WARN: Save Actions not loaded: until build 183.0 < IC-183.5153.38

**Comment by dubreuia** [comment]
Multi release done https://plugins.jetbrains.com/plugin/7642-save-actions/versions

> 1.5.0+2018.3 2018.3+ Apr 17, 2019
> 1.5.0+2016.3 2016.3 — 2018.2.8 Apr 17, 2019

**Comment by xunnanxu** [comment]
@dubreuia this is awesome. Thanks for the effort!
