### ISSUE TITLE
Asterisk mark error

### ISSUE THREAD

**Issue by Luberen** [dubreuia/intellij-plugin-save-actions#147]
I have checked 'Mark modified tabs with asterisk' option, but after I install this plugin, asterisk doesn't disappear even though I saved the file.

It usually occurs when I make new method blocks.

**Comment by Luberen** [comment]
If I press save shortcut twice after make a block, the asterisk mark disappears. But it doesn't disappear at once.

In other situation there's no problem.

IntelliJ IDEA 2017.3.4 (Ultimate Edition)
Build #IU-173.4548.28, built on January 30, 2018
Save Action 0.26

**Comment by Luberen** [comment]
I'm sorry.
I have to save shortcut twice to remove asterisk mark, but it was IDE's problem.

**Comment by dubreuia** [comment]
I received that by email "I'm sorry. I have to save shortcut twice to remove asterisk mark, but it was IDE's problem."

I don't know why it's not showing here, but I'm closing this issue.

Thanks
