### ISSUE TITLE
Ability to perform custom actions on save

### ISSUE THREAD

**Issue by 9point6** [dubreuia/intellij-plugin-save-actions#15]
I'm not sure how feasible this is - but it'd be great if we could trigger an arbitrary menu item on save.

For example, it would be nice to be able to run "JSCS fix" on save

**Comment by dubreuia** [comment]
I'm not sure if it is possible but I'll look into it. It would be very useful to be able to execute any action.

**Comment by dploeger** [comment]
I was just about to add a new feature request on adding a "add final modifier where possible" save-action. But with this feature working it would solve that one, too. So, please, look into it!

**Comment by dubreuia** [comment]
I already developed the feature "add final modifier where possible", I'm testing it right now, I'll release it ASAP.

**Comment by dploeger** [comment]
Cool! Thanks.

**Comment by dubreuia** [comment]
Added in 0.5, please open another issue if you want more custom actions, I'll add them incrementally
