### ISSUE TITLE
No longer working in PyCharm 2018.1.3?

### ISSUE THREAD

**Issue by andy-d** [dubreuia/intellij-plugin-save-actions#153]
Save actions does not seem to be working after upgrading to the most recent PyCharm version 2018.1.3.

Am I the only one seeing this?

FWIW
  (1) I'm on OSX High Sierra
  (2) Don't see anything in PyCharm logs

**Comment by dubreuia** [comment]
It should work, I'll try to test it.

**Comment by andy-d** [comment]
For me it started to work again briefly and then went back to not working. Sadly I've become pretty dependent on it so that my current refractor is full of unused imports. obviously I can use the code refactoring tools built into pycharm directly but it's just no longer a knee jerk

**Comment by dubreuia** [comment]
Just tested in 2018.2.1 and it work. With plugin version 1.0.0

PyCharm 2018.2.1 (Community Edition)
Build #PC-182.3911.33, built on August 5, 2018
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.8.0-59-generic
