### ISSUE TITLE
Organize imports -> optimize imports?

### ISSUE THREAD

**Issue by dallincoons** [dubreuia/intellij-plugin-save-actions#154]
It seems like there's a mismatch of naming conventions in this plugin and the IntelliJ settings. In the plugin the setting is named  "Organize Imports" but the IntelliJ settings name is "Optimize Imports". Is this discrepancy intentional?

**Comment by dubreuia** [comment]
The term in Intellij is "Optimize Imports" and it should be like that everywhere in the plugin. Thanks for pointing it out.

**Comment by dubreuia** [comment]
Fixed https://github.com/dubreuia/intellij-plugin-save-actions/releases/tag/v1.0.0
