### ISSUE TITLE
Add class qualifier to static member access should only apply to other classes

### ISSUE THREAD

**Issue by rw00** [dubreuia/intellij-plugin-save-actions#155]
Please make it configurable to add the class qualifier to only to the classes other than the one where this static member is defined. 

For example, 

```
class Hello { 
   static final String STR="Hello";
   void sayIt() {
     println(STR); // should not qualify it as Hello.STR
   }

   class Other {
      String do() {
         String s = Hello.STR; // should qualify
         return s.replace("l", "y");
       }
   }
}
class World extends Hello {
  void sayIt() {
     println(Hello.STR + " World!"); // should qualify
   }
}
```

Because I didn't find it useful to have
`ThisClassDefinition.log.info("Why so verbose");`

**Comment by dubreuia** [comment]
Hello @rw00, thank you for you interest in the plugin. 

You can submit a PR anytime for this feature. Best way to do that would be to extend the class `com.siyeh.ig.style.UnqualifiedFieldAccessInspection` that is used in the plugin at `com.dubreuia.processors.java.ProcessorFactory#getUnqualifiedFieldAccessProcessor`. 

Check out https://github.com/dubreuia/intellij-plugin-save-actions#contributing to setup your environment.

**Comment by rw00** [comment]
Great! I will. 
Thank you

**Comment by jfcabral** [comment]
Great suggestion @rw00, it's a really much needed feature 👍

**Comment by dubreuia** [comment]
Fixed https://github.com/dubreuia/intellij-plugin-save-actions/releases/tag/v1.0.0
