### ISSUE TITLE
Settings in "Local variable or parameter can be final" are ignored for checks

### ISSUE THREAD

**Issue by kossmoboleat** [dubreuia/intellij-plugin-save-actions#158]
It seems that the save actions plugin doesn't respect the inspection settings when checking if a variable can be final. This currently creates a problem with Lombok `val` values, because those are implicitly final and the behavior in IntelliJ 2018.1. regarding implicit finals changed:

> 1. If "Save Actions" doesn't respect inspection settings, then it must be fixes as it people would expect that their settings do work. Has nothing to do with choosing the desired default: the default here was chosen to keep the old behaviour unchanged (as people tend to complain when after update they get new warnings on the old code from old inspections)

IntelliJ that lead to the changed behavior:
https://youtrack.jetbrains.com/oauth?state=%2Fissue%2FIDEA-182740

lombok-intellij plugin issue:
https://github.com/mplushnikov/lombok-intellij-plugin/issues/469

**Comment by dubreuia** [comment]
Hey @kossmoboleat, thanks for posting. I'll look into it.

**Comment by kossmoboleat** [comment]
Did you find something out about this?

**Comment by dubreuia** [comment]
Hey @kossmoboleat, yes I did, but I won't have time to implement the correction anytime soon. I'm pretty sure it requires me to update the SDK to 2018.1, which by itself isn't a problem, but I'm two years behind... (current 2016.1)

Any help and PR are gladly welcomed. See the README for information on how to contribute 

I understand this is also a request for Java, see recent issue #168.

**Comment by rw00** [comment]
Hi @dubreuia  , 
Could you please describe how to update the SDK? Maybe document it in the README. 

Thanks,

**Comment by SchulteMarkus** [comment]
As #145 is [done](https://github.com/dubreuia/intellij-plugin-save-actions/issues/145#issuecomment-484112199), any update here?

**Comment by dubreuia** [comment]
Yes @SchulteMarkus, this issue can probably be implemented now, just use the master branch (latest SDK version) and I'll backport in the proper version, you can submit a PR.

**Comment by dubreuia** [comment]
Hello guys, is this still present? Closing the issue, please reopen if it is the case.
