### ISSUE TITLE
Run built-in prettier reformatter on save

### ISSUE THREAD

**Issue by dobesv** [dubreuia/intellij-plugin-save-actions#159]
WebStorm has added built-in support for reformatting code using `prettier`.  It would be pretty cool if this plugin could invoke that other plugin on save.

**Comment by dubreuia** [comment]
Hey @dobesv, I know it works for dart, read this paragraph of the docs.

> The code style applied by the save actions plugin is the one configured your settings at "File > Settings > Editor > Code Style". For some languages, custom formatter may also be triggered by the save actions plugin. For example for Dart developers, enable "Use the dartfmt tool when formatting the whole file" option in "File > Settings > Editor > Code Style > Dart > Dartfmt".

If you don't have such options for "prettier", we're out of luck. You can submit a PR to add that feature. See issue #118 where this was already discussed.

**Comment by dubreuia** [comment]
Duplicates #118
