### ISSUE TITLE
Fix current file with ESLint on save

### ISSUE THREAD

**Issue by dobesv** [dubreuia/intellij-plugin-save-actions#160]
WebStorm has some built-in action "Fix current file with ESLint", it would be great to run this action on save.

https://blog.jetbrains.com/webstorm/2016/08/using-external-tools/

**Comment by dubreuia** [comment]
Same as #159.

**Comment by dubreuia** [comment]
Duplicates #118

**Comment by blowsie** [comment]
@dobesv fyi im doing this using a watcher, but its much better suited to a save action.

**Comment by slavco86** [comment]
@blowsie 
Could you share how have you set up file watcher to use ESLint, please?

**Comment by SimenB** [comment]
It's coming natively. Current EAP already supports prettier on save, eslint is coming.

https://blog.jetbrains.com/webstorm/2019/12/webstorm-2020-1-roadmap/

>We also plan to streamline the process of working with Prettier and ESLint by adding options to run them on save and to set Prettier as the default formatter.

**Comment by blowsie** [comment]
@slavco86 
![image](https://user-images.githubusercontent.com/308572/75559258-0d3ea100-5a3b-11ea-878f-47eb46ced493.png)

**Comment by slavco86** [comment]
Massive! Thank @blowsie
