### ISSUE TITLE
Jumping Cursor when Reformat File is on

### ISSUE THREAD

**Issue by Christian-Seiler** [dubreuia/intellij-plugin-save-actions#162]
When "Reformat File" is on, whenever I save, the cursor is jumping back about 4 characters. This is rather annoying to work with.

**Comment by dubreuia** [comment]
Hey @Christian-Seiler, thanks for posting. 

I just tested in the following version and I cannot reproduce. Can you screencast the problem and give me the keypresses that creates the issue and the version of your IDE.

IntelliJ IDEA 2017.3.4 (Ultimate Edition)
Build #IU-173.4548.28, built on January 29, 2018
Licensed to Courtanet / Alexandre Dubreuil
Subscription is active until November 22, 2018
JRE: 1.8.0_152-release-1024-b11 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.8.0-59-generic

**Comment by Christian-Seiler** [comment]
Below you can find my settings and screencast

IntelliJ IDEA 2018.1.4 (Ultimate Edition)
Build #IU-181.5087.20, built on May 16, 2018
Licensed to Christian Seiler
Subscription is active until September 11, 2018
For educational use only.
JRE: 1.8.0_152-release-1136-b39 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.4

<img width="1030" alt="settings" src="https://user-images.githubusercontent.com/5319752/40918300-2fe7ca3e-6806-11e8-8eb1-3e23d461ff22.png">

[Jumping Cursor.zip](https://github.com/dubreuia/intellij-plugin-save-actions/files/2068267/Jumping.Cursor.zip)

**Comment by dubreuia** [comment]
Are you sure it comes from save-actions? Can you deactivate and check if issue is still present?

**Comment by Christian-Seiler** [comment]
I have tried this before. As soon as I deactivate `reformat file` the issue is resolved

**Comment by dubreuia** [comment]
Cannot reproduce
