### ISSUE TITLE
State property misarrangement in React components with latest versions of WebStorm & Save actions plugin

### ISSUE THREAD

**Issue by unlabeled** [dubreuia/intellij-plugin-save-actions#164]
I have WebStorm 2018.1.5, Save actions plugin v0.26 with Ts arrangement settings like: Property Private -> Property Public -> constructor -> Method Private -> Method Public.
Code like this:
```jsx
class TestComponent extends React.Component<Props, State> {
    param: any;
    private privateParam: any;
    state: State;
    render () {return null;}
}
```
Becomes:
```jsx
class TestComponent extends React.Component<Props, State> {
    private privateParam: any;
    param: any;
    render () {return null;}
    state: State;
}
```
Everything works fine but state goes to the very end of the class declaration.

**Comment by dubreuia** [comment]
The save-actions plugin doesn't do anything else then calling the `RearrangeCodeProcessor` from Jetbrains that is configured with "Settings > Editor > Code Style > * > Arrangement". I'm pretty sure it isn't a save-actions problem. Can you execute rearrange code on the first snippet ("CTRL + SHIFT + A > Rearrage") ? If you get the same then the second snippet, then it is not a save-actions issue.

**Comment by unlabeled** [comment]
Yep, you're right. It works the same way with just code rearrange.
