### ISSUE TITLE
Feature Request: Generate serialVersionUID

### ISSUE THREAD

**Issue by Delfic** [dubreuia/intellij-plugin-save-actions#165]
I would like to request for the option to include the quick-fix regarding the generation of serialVersionUID.

The following inspection can be used to implement such a feature:

![generateserialversionuid](https://user-images.githubusercontent.com/4091284/41854319-d4c6ebd4-7887-11e8-80fe-68bac61590d2.png)

Thanks in avance,
Delfic

**Comment by dubreuia** [comment]
Hey @Delfic, there are two inspections from Intellij that we could use for this one:

- `com.siyeh.ig.fixes.AddSerialVersionUIDFix`
- `com.siyeh.ig.serialization.NonSerializableWithSerialVersionUIDFieldInspection.RemoveSerialVersionUIDFix` (but it is private)

You can submit a PR anytime.

**Comment by rw00** [comment]
@dubreuia  , 
Please assign this issue to me. I will submit tonight.

**Comment by dubreuia** [comment]
:+1:
