### ISSUE TITLE
Feature Request: Don't add final to implicitly final elements.

### ISSUE THREAD

**Issue by thecatwhisperer** [dubreuia/intellij-plugin-save-actions#168]
### Summary
Currently**Save Actions** will add the final keyword to all relevant variables, etc.  However, it may not desirable to have it add final to variables, etc, that are implicitly final (try-with-resources, etc).

**Comment by dubreuia** [comment]
Hey @thecatwhisperer, excellent idea. You can submit a PR anytime. Please check the README for information on how to contribute.

**Comment by dubreuia** [comment]
It is implemented here: https://github.com/studouglas/intellij-plugin-save-actions/commit/16706a908e63219fc58da71cc1f1eee9acc6030f

Don't know why no PR has been submitted here

**Comment by mateuszwinnicki** [comment]
@dubreuia I created PR with fix and test, take a look please

**Comment by dubreuia** [comment]
Thanks a lot for the PR #232. Really unsure about bumping SDK to version 2018 though.

Review pending please check comments.

**Comment by dubreuia** [comment]
Bumping to 2018.1 SDK means we're not supporting perpetual fallback for 2016, 2017. Latest release for 2017 was 6 months ago, 2016 1 year ago. I fell like we should support that. See https://www.jetbrains.com/idea/download/previous.html

I'm reopening #145

**Comment by mateuszwinnicki** [comment]
The main problem is that parameter REPORT_IMPLICIT_FINALS is introduced in 2017.2 version. But even if this parameter is set to true test I wrote is not failing. It needs further investigation why 2017.2 is actually not adding final to a resource (maybe test is wrongly created).

I don't see any additional comments in PR

**Comment by dubreuia** [comment]
Still need #145 to release

**Comment by chriswhite199** [comment]
What's the latest on this issue? I'm still seeing final being added to try-with-resources blocks in 2020.1 and SaveActions 2.0.0. Is there explicit configuration required (i have all 3 'Add final modifier ...' options checked in the settings

**Comment by mateuszwinnicki** [comment]
If you have checked "Add final modifier to local variables or parameter" AND "Add final modifier to local variables or parameter except if it is implicit" it will add final to try-with-resources, because both rules will work. Use one of them only and it will work fine.

**Comment by chriswhite199** [comment]
Makes sense now - so only check the _Add final modifier to local variable or parameter except if it is implicit_.

Would it ever make sense to check both? If not then it might be worth adding some mutually exclusive validation to those two checkboxes

**Comment by dubreuia** [comment]
@chriswhite199 I've opened an issue as a bug to fix that, I also think the both checkboxes should be mutually exclusive
