### ISSUE TITLE
Run actions manually

### ISSUE THREAD

**Issue by 0xbaadf00d** [dubreuia/intellij-plugin-save-actions#169]
Please add option to run manually "actions" (on all file: changed and un-changed) like the builtin "re-arrange code". to avoid opening 500 java files to run actions on it.

**Comment by dubreuia** [comment]
I understand this would be useful, but it is a "save" action plugin, so this is out of scope for now.

AFAIK, you can right click on the project root, then choose "reformat" in the context menu, and you can format all files from the popup. If you need more actions then what you have there, you should ask for a feature request to Jetbrains.

**Comment by 0xbaadf00d** [comment]
I'm sorry but as long your plugin dont use builtin reformat rules (your plugin add automatically "this." or "final", IntelliJ reformat: not), your workaround is not acceptable.

**Comment by dubreuia** [comment]
Let's make some things clear:

- I'm not implementing anything here. If you want a feature, you can submit a PR, and I'll merge it if I think it's good. This is how open source works. I'm not Jetbrains, I'm doing this on my free time.
- I get to decide what is an acceptable feature for this project. This one isn't. We can have a constructive argument about whether or not this feature will eventually make it to master, but right now, you haven't convinced me.
- The plugin actually uses builtin reformat and quick fixes (final, etc.), I haven't written any. I just "glued" them to the save action. Check `https://github.com/dubreuia/intellij-plugin-save-actions/blob/master/src/main/java/com/dubreuia/processors/java/ProcessorFactory.java` (all the import for the quick fixes are from Intellij code).

**Comment by dubreuia** [comment]
Merged in master, added to 1.1.0
