### ISSUE TITLE
Feature request: Autosave support

### ISSUE THREAD

**Issue by Gerdon262** [dubreuia/intellij-plugin-save-actions#186]
Currently Save Actions will trigger when the user saves the file.

What I would love to see, if that is possible, is that Save Actions will trigger before / after IntelliJ auto saves the file.
This way everything is automated and no user action is required

**Comment by dubreuia** [comment]
Hello. This is the whole point of this plugin: it is triggered on autosave, no user action is required. Intellij saves the file when:

- the IDE loses focus (this is called frame deactivation)
- the IDE reaches a timeout of inactivity (this is disabled by default)

If you want to try it for yourself: edit a file that is not formated, alt-tab to another window, come back to IDE, you'll find your file formated.
