### ISSUE TITLE
Save action not working for new files which are not added in git for Intellij

### ISSUE THREAD

**Issue by vijay40** [dubreuia/intellij-plugin-save-actions#188]
Hi, 

After the recent update of save actions, it is not working for files which are not yet checked into GIT or is a part of some commit. It works perfectly for the files which are already a part of some commit. I am working in intellij IDEA community edition 2018.2.2 on mac.

Let me know if more information is required to reproduce the bug. 

Thanks
Vijay

**Comment by dubreuia** [comment]
Just tested on 2018.2.3 and save-actions 1.1.0: (1) add new java file Test.java without adding to git (2) add unused import (3) lose focus (4) the import is correctly removed.

Can you post the content of the config file `.idea/saveactions_settings.xml` and log `~/.IntelliJIdea2018.2/system/log/idea.log`
