### ISSUE TITLE
Failed plugin initialize 

### ISSUE THREAD

**Issue by szymek204** [dubreuia/intellij-plugin-save-actions#19]
![pluginerror](https://cloud.githubusercontent.com/assets/14124484/9681568/4778c924-52ff-11e5-89c7-9fbc1ff96cac.PNG)

**Comment by dubreuia** [comment]
Could you give me Intellij version / OS please? Did you install the plugin from the plugin management screen in Intellij ?

**Comment by dubreuia** [comment]
Cannot reproduce / lack of information I'm closing the issue
