### ISSUE TITLE
Android Studio Invalid, save format invalid

### ISSUE THREAD

**Issue by wangjianfengw** [dubreuia/intellij-plugin-save-actions#191]
View to activate, cannot format the code when saved, no problem before 1.00 version, 1.00 version cannot format the code!

**Comment by dubreuia** [comment]
Hello @wangjianfengw, I need more info to understand your problem. Can you please be more precise: 

- What is the plugin configuration? Can you post the file .idea/saveactions_settings.xml?
- What where you expecting? Can you post the file content before and after save-actions?
- Do you see a stack trace?

**Comment by wangjianfengw** [comment]
![image](https://user-images.githubusercontent.com/20201762/45463834-5cf2b500-b740-11e8-80a3-7f9f0f2aecc6.png)

**Comment by wangjianfengw** [comment]
> 您好@wangjianfengw，我需要更多信息来了解您的问题。你能更精确地说：
> 
> * 什么是插件配置？你能发帖子.idea / saveactions_settings.xml吗？
> * 你期待什么？你能在保存动作之前和之后发布文件内容吗？
> * 你看到堆栈跟踪了吗？

![image](https://user-images.githubusercontent.com/20201762/45463922-b2c75d00-b740-11e8-8bfc-773bb59c5e8b.png)

**Comment by dubreuia** [comment]
Ok thank you for sending your configuration. What is the problem? The code is not properly formated? The plugin works this way: if a file needs formatting, the plugin will format it when you change window.

You have "No action if compile error" selected. You can remove that in case this is the problem.

Can you send the content of the file "~/.IntelliJIdea2018.2/system/log/idea.log"?

---

好的，谢谢你发送配置。问题是什么？代码格式不正确？插件以这种方式工作：如果文件需要格式化，插件将在您更改窗口时对其进行格式化。

如果选择了“编译错误，则无操作”。如果这是问题，您可以删除它。

你能发送文件“〜/ .IntelliJIdea2018.2 / system / log / idea.log”的内容吗？

**Comment by dubreuia** [comment]
Also if you are not using "git" or "cvs" or "svn" in intellij, remove the option "Reformat only changed code" because it won't work.

--- 

此外，如果您未在intellij中使用“git”或“cvs”或“svn”，请删除“仅重新格式化已更改的代码”选项，因为它不起作用。

**Comment by wangjianfengw** [comment]
[idea.log](https://github.com/dubreuia/intellij-plugin-save-actions/files/2382011/idea.log)

**Comment by dubreuia** [comment]
The plugin is correctly triggered: your file should be cleaned of unused imports and reformated.

```
2018-09-14 10:24:42,224 [cessToken]]  DEBUG - re.component.SaveActionManager - Running SaveActionManager on DocumentImpl[file://D:/Work/HeartUser/HeartUser/app/src/main/java/com/lc/sxn/BaseApplication.java] 
2018-09-14 10:24:42,234 [cessToken]]  DEBUG - re.component.SaveActionManager - Running processors [RearrangeCode (false), OptimizeImports (true), ReformatChangedText (true), Compile (false)], file PsiJavaFile:BaseApplication.java, project Project 'D:\Work\HeartUser\HeartUser' HeartUser 
```

But it seems you have a "build.gradle", there is a bug on gradle build files: #184. 

```
2018-09-14 08:46:34,099 [cessToken]]  DEBUG - re.component.SaveActionManager - Running SaveActionManager on DocumentImpl[file://D:/Work/dragon_mining_campus/project/WorkPlaceRuler/app/build.gradle] 
```

Try excluding it: ![screenshot from 2018-09-14 10-58-26 exclude](https://user-images.githubusercontent.com/657731/45540657-4cf4d700-b80d-11e8-8673-736425efc9a7.png)

**Comment by wangjianfengw** [comment]
I tried five or six projects that could not be formatted, so they should have nothing to do with build.gradle

**Comment by dubreuia** [comment]
Need more info, reopen if necessary
