### ISSUE TITLE
Generalize inspections

### ISSUE THREAD

**Issue by dubreuia** [dubreuia/intellij-plugin-save-actions#195]
I feel like inspections / quick fixes are a way to reach a broader audience with save-actions. There is a lot already available in intellij for many langagues, it is just a matter of gluing them in the plugin. I'd like to add an inspection panel to save-actions:

![screenshot from 2018-09-19 11-42-04](https://user-images.githubusercontent.com/657731/45745772-dfc4b580-bc01-11e8-93b4-f60758279f40.png)

- Generalize storage and actions for any language
- Remove checkboxes and add panel to UI
- Streamline addition of new inspection (partially done)

**Comment by markiewb** [comment]
You could execute an inspection profile within the plugin.

The user can define his inspections within a profile using the built-in
dialogs, save this profile and configure the plugin to use the profile. The
plugin configuration requires a drop down, which shows all available
profiles, to do this. I am guessing that the API isn't public, but you
could still access it.

Nevertheless I would not complety replace the current state of checkboxes
with this profile approach. Add it as an option. Users like me still use
the external epf-configuration files and can't switch to the "check in the
saveactions.xml configuration to git" approach for collaboration reasons.
Or create an in-memory profile from the epf-file every time the save action
is triggered.

**Comment by dubreuia** [comment]
Defining inspections within a profile is a good idea. Probably a bit more dev but why not.

Not a fan of having both checkboxes and profiles approach. In any case, support of Eclipse epf file is important and it needs to be supported.

**Comment by dubreuia** [comment]
Closing, too broad
