### ISSUE TITLE
"Reformat only changed code" is not working

### ISSUE THREAD

**Issue by chengren311** [dubreuia/intellij-plugin-save-actions#196]
**Describe the bug**
When it's enabled,  lines of code that are not being changed are also reformatted.

**Versions**
2018.2

**Attachments**
plugin setting:
![image](https://user-images.githubusercontent.com/1428327/46046416-ce821a00-c0d5-11e8-91db-ee0bb46b8c38.png)

before change
![image](https://user-images.githubusercontent.com/1428327/46046477-130db580-c0d6-11e8-9010-934fc72d7c2b.png)

added one extra semicolon 
![image](https://user-images.githubusercontent.com/1428327/46046495-24ef5880-c0d6-11e8-95d0-e1ba625a187e.png)

applied save, first line gets changed as well: 
![image](https://user-images.githubusercontent.com/1428327/46046590-7ac40080-c0d6-11e8-8487-dbe8885da17c.png)

**Comment by chengren311** [comment]
hi @dubreuia 
```do you have VCS (git, svn, etc.) configured?```
yes, i use git. 
```When you say "applied save", what do you mean?```
Meaning i saved my change.

**Comment by ssyang0102** [comment]
When will this problem be solved？

**Comment by dubreuia** [comment]
I couldn't reproduce, I just figured out why: the option "Reformat only changed code" works with **reformat** only. There is no option "Quick fix only changed code" for now. See #35

**Comment by dubreuia** [comment]
@developerlover See the new issue #217
