### ISSUE TITLE
Deactivate code modification while typing 

### ISSUE THREAD

**Issue by dubreuia** [dubreuia/intellij-plugin-save-actions#2]
https://www.reddit.com/r/IntelliJIDEA/comments/2qta03/intellij_save_action_plugin_just_released/

> Tested it now with CE 14.0.2 for a few minutes. It does change the code under my hands, quite often even (every 15 seconds or more). If this machine weren't too slow for such a feature, anyway, I would probably not suffer it, though. Will try again at home (might not report), where it's really fast, deactivated it here (office).

**Comment by krasa** [comment]
Perhaps you should hook on FileEditorManagerListener#fileClosed and on FrameStateListener#onFrameDeactivated

**Comment by dubreuia** [comment]
Thanks @krasa! I'll look into that.

**Comment by krasa** [comment]
That is one interesting issue, so I am poking into it a little more... 

I would not process the currently active editor unless the save is triggered manually, like so: 
https://github.com/dubreuia/intellij-plugin-save-actions/compare/master...krasa:deactivateCodeModificationWhileTyping?expand=1

Hopefully if something saves the file automatically from the background while typing, it would not go through the SaveAllAction.

**Comment by dubreuia** [comment]
I read your commit but didn't have time to test it, I'll check it it out as soon as I can. Thanks a lot.

**Comment by dubreuia** [comment]
I merged your pull request @krasa it should correct the issue. I'm closing it

**Comment by dubreuia** [comment]
Added in 0.5
