### ISSUE TITLE
Don't reformat unmodified lines in IDEA 15

### ISSUE THREAD

**Issue by PROrock** [dubreuia/intellij-plugin-save-actions#20]
plugin is forcing style rules of javadoc (adding empty lines) and line break when overflowing specified Right margin
this happens in IDEA 15, in IDEA 14.1.5 plugin works fine

**Comment by dubreuia** [comment]
I have the problem too, I think 15 is now enforcing javadoc style rules that 14 didn't (it might be normal behavior). I'll check it out.

**Comment by Toilal** [comment]
As a workaround, you can configure the formatting with CTRL+ALT+SHIFT+L and change the scope. It seems to be kept for later calls performed by the plugin.

**Comment by dubreuia** [comment]
will not fix
