### ISSUE TITLE
Execute save actions on multiple files not working

### ISSUE THREAD

**Issue by burgerkingeater** [dubreuia/intellij-plugin-save-actions#200]
**Describe the bug**
I would expect this would reformat every file in my project:
![image](https://user-images.githubusercontent.com/1428327/46896502-3b194a80-ce32-11e8-8f8a-a48ecf0f3826.png)
but nothing really changes after clicking OK. Am i missing anything here? Thanks!

**Versions**
Intellij 2018.2

**Comment by dubreuia** [comment]
@chengren311 This should work, what is your save-actions configuration? Can you post the screenshot of your configuration or your config file? Does the plugin works normally?
