### ISSUE TITLE
Reformat appears for one second and disappears again

### ISSUE THREAD

**Issue by ghost** [dubreuia/intellij-plugin-save-actions#204]
**Describe the bug**
On Intellij 2018, OS Linux Mint. I installed the plugin freshly and also configured the settings. After pressing Ctrl + Shift + S the effects occur, however only for one second and they disappear again.

Edit: Apparently when I use the option to auto save on whole project, it start like 30-40 processes and my Computer becomes extreme hot. 

**To Reproduce**
Well, that is basically the description of the bug.Especially the parameters of a method should be final but it is not and it really bugs me.

**Expected behavior**
I expected the changed to stay persistently and not disappear. Specially

**Screenshots (optional)**
No Screenshots since the time interval is very short

**Versions**
IntelliJ 2018.3.1

**Stack Trace**

> java.lang.Throwable: Short name not matched for class me.maiyuan.cleancode.InstanceFieldCountInspection: getShortName() = #me.maiyuan.cleancode.InstanceFieldCountInspection; ep.shortName = #InstanceFieldCount
> 	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:123)
> 	at com.intellij.codeInspection.ex.InspectionToolWrapper.getTool(InspectionToolWrapper.java:72)
> 	at com.intellij.codeInspection.ex.ScopeToolState.areSettingsEqual(ScopeToolState.java:124)
> 	at com.intellij.codeInspection.ex.ScopeToolState.equalTo(ScopeToolState.java:117)
> 	at com.intellij.codeInspection.ex.ToolsImpl.equals(ToolsImpl.java:453)
> 	at com.intellij.openapi.util.Comparing.equal(Comparing.java:45)
> 	at com.intellij.codeInspection.ex.InspectionProfileImpl.toolSettingsAreEqual(InspectionProfileImpl.java:107)
> 	at com.intellij.codeInspection.ex.InspectionProfileImpl.getChangedToolNames(InspectionProfileImpl.java:804)
> 	at com.intellij.codeInspection.ex.InspectionProfileImpl.writeExternal(InspectionProfileImpl.java:229)
> 	at com.intellij.codeInspection.ex.InspectionProfileImpl.writeScheme(InspectionProfileImpl.java:200)
> 	at com.intellij.codeInspection.ex.InspectionProfileImpl.writeScheme(InspectionProfileImpl.java:190)
> 	at com.intellij.configurationStore.LazySchemeProcessor.writeScheme(scheme-impl.kt:70)
> 	at com.intellij.configurationStore.LazySchemeProcessor.writeScheme(scheme-impl.kt:61)
> 	at com.intellij.configurationStore.SchemeManagerImpl.saveScheme(SchemeManagerImpl.kt:436)
> 	at com.intellij.configurationStore.SchemeManagerImpl.save(SchemeManagerImpl.kt:382)
> 	at com.intellij.configurationStore.SchemeManagerFactoryBase.save(SchemeManagerFactoryImpl.kt:91)
> 	at com.intellij.configurationStore.ComponentStoreWithExtraComponents.afterSaveComponents(ComponentStoreWithExtraComponents.kt:38)
> 	at com.intellij.configurationStore.ComponentStoreImpl.save(ComponentStoreImpl.kt:137)
> 	at com.intellij.openapi.components.impl.stores.StoreUtil.save(StoreUtil.java:40)
> 	at com.intellij.openapi.project.impl.ProjectImpl.save(ProjectImpl.java:331)
> 	at com.intellij.openapi.project.impl.ProjectImpl.save(ProjectImpl.java:315)
> 	at com.intellij.compiler.impl.CompileDriver.a(CompileDriver.java:382)
> 	at com.intellij.compiler.impl.CompileDriver.a(CompileDriver.java:365)
> 	at com.intellij.compiler.impl.CompileDriver.compile(CompileDriver.java:149)
> 	at com.intellij.compiler.CompilerManagerImpl.compile(CompilerManagerImpl.java:233)
> 	at com.intellij.compiler.CompilerManagerImpl.compile(CompilerManagerImpl.java:223)
> 	at com.dubreuia.processors.CompileProcessor.lambda$run$0(CompileProcessor.java:33)
> 	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
> 	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:447)
> 	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:431)
> 	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
> 	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
> 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
> 	at java.awt.EventQueue.access$500(EventQueue.java:98)
> 	at java.awt.EventQueue$3.run(EventQueue.java:715)
> 	at java.awt.EventQueue$3.run(EventQueue.java:709)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
> 	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:781)
> 	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:722)
> 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
> 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by dubreuia** [comment]
Can you post your settings please? See https://github.com/dubreuia/intellij-plugin-save-actions#files-location

Also if you configured a quick fix add and also removal, the removal wins (see https://github.com/dubreuia/intellij-plugin-save-actions#java-fixes). I'm pretty sure it is what happens.

Does the stack trace happens a lot? You sure it is from the plugin? You should remove the compiler action if you have it activated.
