### ISSUE TITLE
Deactivate "compile" and "reload" (StackOverflowError)

### ISSUE THREAD

**Issue by dubreuia** [dubreuia/intellij-plugin-save-actions#209]
- "Compile" is still async (this breaks "reload")
- "Compile" and "reload" should be exclusive

**Comment by dubreuia** [comment]
- There's a double reload (first reload with nothing, then it gets compiled and the second reload is ok)

**Comment by dubreuia** [comment]
The compile action still triggers too much, see related issue.

**Comment by dubreuia** [comment]
> "It triggers a recompilation 135 times on each triggering."

That might be a problem

**Comment by dubreuia** [comment]
Seeing how buggy this is, I'll just deactivate the feature

**Comment by kangarko** [comment]
Let's talk money, we can pay you to fix this problem. Contact us at matej@mineacademy.org

**Comment by dubreuia** [comment]
Hello @kangarko, thank you for your offer, but I have a time problem, not a money problem. If I ever find time to do this, you'll be the first to know.

**Comment by kangarko** [comment]
Alright thanks!

**Comment by dubreuia** [comment]
I'll release a fix in 1.8.0, based on the PR for #246. Tell me if that's what you had in mind @kangarko.

**Comment by dubreuia** [comment]
Released in [1.8.0](https://github.com/dubreuia/intellij-plugin-save-actions/releases/tag/v1.8.0).
