### ISSUE TITLE
Save actions reformat the whole file in refactoring operations even with reformat only changed code turned on

### ISSUE THREAD

**Issue by MANGO1234** [dubreuia/intellij-plugin-save-actions#21]
Intellij 14/15, Windows 7. Refactor e.g. a Java class name will reformat the whole file for any file that uses that class even with Reformat only changed code turn on.

**Comment by dubreuia** [comment]
OK I'll check it out.

**Comment by dubreuia** [comment]
@MANGO1234 Could you check if you have a VCS configured? Like git or svn or something.

**Comment by dploeger** [comment]
It could be, that @MANGO1234 is not referring to the reformat options but to the "Inspections quick fix"-options. I have the same problem here.

Could you please support a "fix only change lines" also for the "Inspection quick fix"-options?

**Comment by dubreuia** [comment]
I think the current behaviour is: if "only change lines" is active but VCS is not configured, then the plugin reformat the whole file (maybe it should reformat nothing).

For the inspection quick fix, I will add a "only change lines" option, I actually need it too.

**Comment by dubreuia** [comment]
Added can't activate "only change lines" if VCS not configured (#34) and I'll correct the whole file behavior in this issue

**Comment by dubreuia** [comment]
Added "only change lines" issue: #35

**Comment by dubreuia** [comment]
will not fix
