### ISSUE TITLE
Add activation options "after timeout" and "on editor change"

### ISSUE THREAD

**Issue by dubreuia** [dubreuia/intellij-plugin-save-actions#215]
See #211 for context:

- **after timeout**: if no key is pressed for x seconds, trigger save actions
- **on editor change**: when the file editor changes (basically switching to another file), trigger save actions

**Comment by dubreuia** [comment]
Reword the activation option to explain "frame deactivation".

**Comment by simonmarshall** [comment]
i would add that this new after-timeout save-actions behaviour should respect the "No action if compile errors" flag.

one thing i noticed with the consequence of https://github.com/dubreuia/intellij-plugin-save-actions/issues/211 (which i previously assumed was the default/correct save-actions behaviour) was that the reformatting always occurred even if the source file contained syntax errors.  this can be annoying if you pause editing, leaving an inevitable syntax error in partially-written code, such that save-actions kicks in and reformats, where reformatting typically combines the current line (with its syntax error) with the following line(s).

**Comment by dubreuia** [comment]
Good idea about the "no action if compile error". I also noticed the plugin is triggered before some refactoring actions, not sure this is good or not.

**Comment by dubreuia** [comment]
Moved to ideas https://github.com/dubreuia/intellij-plugin-save-actions/projects/2
