### ISSUE TITLE
Reformat whole file always triggered

### ISSUE THREAD

**Issue by dubreuia** [dubreuia/intellij-plugin-save-actions#217]
Even if VCS is activated and configured. See #216

**Comment by filipstimac** [comment]
I just updated to 1.4 and it seem that it's still triggering whole file reformat. Are you sure it's resolved?

**Comment by dubreuia** [comment]
LGTM

Can you check your settings?

**Comment by filipstimac** [comment]
Okay, I'm 100% positive now, VCS correctly setup, setting also, both are not touched since I used while switching between 1.2 and 1.4. Any change in file still triggers whole file reformat on IntelliJ.

**Comment by dubreuia** [comment]
@filipstimac I'm pretty sure the option "Reformat" in your settings is activated. Can you send me your settings.xml please?

**Comment by developerlover** [comment]
This is my settings.xml. For me it is happening the same. What is the "Reformat" option you are talking about?

[settings.zip](https://github.com/dubreuia/intellij-plugin-save-actions/files/2803858/settings.zip)

**Comment by dubreuia** [comment]
Sorry I meant the save action settings file, check https://github.com/dubreuia/intellij-plugin-save-actions#files-location. Or screenshot the settings page. There are two options

- "Reformat file"
- "Reformat only changed code"

To reformat only changed code:

- if you are on latest 1.4.0, you need to have only "Reformat changed code" selected.
- if you are on 1.3.0, you need to have both "Reformat file" and "Reformat only changed code"

**Comment by dubreuia** [comment]
I'm releasing 1.4.0 soon, you can find it in the release section

**Comment by filipstimac** [comment]
Okay, I'm 100% positive now, VCS correctly setup, setting also, both are not touched while switching between 1.2 and 1.4. Any change in file still triggers whole file reformat on IntelliJ.

**Comment by filipstimac** [comment]
Everything working fine, didn't realize that you changed settings. Now only "Reformat only changed code" is needed. Thanks a lot!

**Comment by developerlover** [comment]
Ok, thank you! I have the 1.3.0. So, I'll wait to the 1.4.0 :)

**Comment by piRGoif** [comment]
Hello, thanks for the fix, I was very worried about it and wasn't using Save Actions since some time now !

Just a suggestion though, I find the UI a bit tricky : You need to check "Reformat file" to be able to check "Reformat only changed code", then you have to uncheck "Reformat file". The 2nd option depends on the first, which is not very logical... Might the dependency be reversed ? Or maybe have radio buttons instead of checkboxes for those 2 options ?
I'm asking for advice here instead of creating a new issue O:)

**Comment by filipstimac** [comment]
That was changed with 1.4, now if you want to reformat just changed part of the code you check only "Reformat only changed code", if you check both on 1.4 you'll still get the whole file reformat. Those two check boxes are now independent, but whole file reformat overrides just changed code if bot are checked.

**Comment by piRGoif** [comment]
Wooops sorry my mistake I missed the 1.4.0 update, I've now installed it and can see that the 2 options are independant now !
Apologies, I was confused by the new plugins presentation and misread the installed version...
Thanks @filipstimac !

**Comment by dubreuia** [comment]
Yeah this should be radio buttons but I didn't have time to do it, I wanted to fix first. I'll open another issue for the wierd ui

**Comment by dubreuia** [comment]
Created #223

**Comment by wildd** [comment]
Hi, I still have this problem. Tried to switch between options several times, restarted IDE several times. I have VCS configured. I even uninstalled plugin, deleted "saveactions_settings.xml" under project, installed again plugin, but still same problem - not changed code gets formatted on every file save.
Whats even interesting, before update when I had option both reformat options selected, I think I could press "cmd+z", then "cmd+s" and file got saved only with my changes, without auto changes, but now even this doesn't work on every save everything gets formated, need to manually discard hunks in git.

Save Actions v1.4.0

IntelliJ IDEA 2018.3.4 (Ultimate Edition)
Build #IU-183.5429.30, built on January 29, 2019
JRE: 1.8.0_152-release-1343-b26 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.11.6

**Comment by dubreuia** [comment]
@wildd Can you send your "saveactions_settings.xml" file please?

**Comment by xunnanxu** [comment]
@dubreuia same issue with @wildd 
Only reformat changed code is enabled. VCS (git) is enabled. But still the whole file is modified.

```
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="SaveActionSettings">
    <option name="actions">
      <set>
        <option value="activate" />
        <option value="noActionIfCompileErrors" />
        <option value="organizeImports" />
        <option value="reformatChangedCode" />
        <option value="fieldCanBeFinal" />
        <option value="localCanBeFinal" />
        <option value="missingOverrideAnnotation" />
        <option value="useBlocks" />
      </set>
    </option>
    <option name="configurationPath" value="" />
  </component>
</project>
```
