### ISSUE TITLE
unable to configure the plugin from an Eclipse .epf file with the last versions (1.3.0+)

### ISSUE THREAD

**Issue by jgraglia** [dubreuia/intellij-plugin-save-actions#218]
With the last versions (1.3.0, 1.4.0), I could no longer use a .epf file to configure the plugin. 
The FileChooser require a .java file

**To reproduce**
Update to at least to version 1.3.0 : the config panel now require a .java file for the Eclipse support"

**Expected behavior**
I should still be able to use a .epf file to configure the plugin.

**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/754914/51760816-b80fbd80-20cb-11e9-89f0-ae2b454ca8ab.png)

**Versions**
IntelliJ IDEA 2019.1 EAP (Ultimate Edition)
same with 2018 IDEAJ

I have tracked down the changes to the commit e04a3d21e4952f4050d83543b08f2316ec4310b2#diff-7b45384a530217cf987bff767403cda1R61
It seems to me that it is due to a big refactoring. I have found that _com.dubreuia.model.epf_ package was renamed to _com.dubreuia.model.java_  in this commit and may be this was a non desired change.
I can only find a EpfStorage class,

**Comment by dubreuia** [comment]
Thanks for opening the issue. I'll fix in 1.4.0 in the beginning of next week.

**Comment by dubreuia** [comment]
Done

**Comment by jgraglia** [comment]
Hi, I was waiting for the plugin to be available in the plugins repository : it is done today and I have applied the update : I can confirm this is fixed.

Thank you !
