### ISSUE TITLE
Make save actions shortcut customizable

### ISSUE THREAD

**Issue by piRGoif** [dubreuia/intellij-plugin-save-actions#219]
The default save action shortcut is Ctrl+Shift+S
This shortcut is already assigned to refactor/copy file in PHP Storm, and the existing one cannot be deleted nor re-assigned :(

**Comment by dubreuia** [comment]
Reassign it with "File > Settings > Keymap > Plug-ins > Save Actions > Execute Save Actions on shortcut".
