### ISSUE TITLE
Unmodified lines being formatted in PHPStorm 2018.3.3

### ISSUE THREAD

**Issue by minitauros** [dubreuia/intellij-plugin-save-actions#221]
**Describe the bug**
On save, Save Actions formats the file as configured. But it also formats the unmodified lines, which it is configured not to do.

Tried reinstalling (uninstall, restart, install, restart). Did not work.

I cannot recall when it started misbehaving and if it could have anything to do with me changing settings (can't recall changing settings, so I assume it can't).

**To Reproduce**
Run PHPStorm 2018.3.3. Check 4 checkboxes of the Save Actions config:

- Activate save actions on save
- Optimize imports
- Reformat file
- Reformat only changed code (if VCS configured)

**Expected behavior**
Reformat only changed code.

**Versions**
PS183.5153.46 January 9, 2019

**Attachments**
[idea.log](https://github.com/dubreuia/intellij-plugin-save-actions/files/2811738/idea.log)

[saveactions_settings.xml.zip](https://github.com/dubreuia/intellij-plugin-save-actions/files/2811740/saveactions_settings.xml.zip)

**Comment by dubreuia** [comment]
You need to check only "reformat changed lines". Actually you can't select both.

**Comment by minitauros** [comment]
It works! Funny though, because I never touched these settings and it used to work the way I had configured it. Thanks for the support anyway!

**Comment by dubreuia** [comment]
Yeah behavior changed in 1.4.0, sorry about that. Cheers.
