### ISSUE TITLE
Method call beforeAllDocumentsSave do not return unsaved documents

### ISSUE THREAD

**Issue by N3XT0R** [dubreuia/intellij-plugin-save-actions#224]
**Describe the bug**
Hello Guys, since i've updated to version 1.4 of this plugin inside of PhpStorm, the save action do nothing anymore. 

**To Reproduce**
Look at the screenshot for configuration. 

**Expected behavior**
Normally it should reformat the sourcecode on save. 

**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/1297846/52064510-0e21ac80-2575-11e9-9d15-5c28e3a8297a.png)

**Versions**
PhpStorm 2018.3.3
Build #PS-183.5153.36, built on January 9, 2019
Licensed to Alpha Online Service GmbH / Ilya Beliaev
Subscription is active until September 19, 2019
JRE: 1.8.0_152-release-1343-b26 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Attachments**

`
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="SaveActionSettings">
    <option name="actions">
      <set>
        <option value="activate" />
        <option value="reformat" />
      </set>
    </option>
    <option name="exclusions">
      <set>
        <option value="/*.tpl" />
        <option value="Ignore\*.tpl" />
      </set>
    </option>
  </component>
</project>
`

Attach 2 files from https://github.com/dubreuia/intellij-plugin-save-actions#files-location

**Comment by dubreuia** [comment]
I'll need more info, can you send me a copy of your "idea.log" (https://github.com/dubreuia/intellij-plugin-save-actions#files-location). You can filter the lines that do not belong to the plugin with `sed -n '/SaveActionManager/p' idea.log`.

Also, are you sure it doesn't work? Test this: modify a file, click in another window (like here), then return to the IDE, and check if your code is formatted.

**Comment by N3XT0R** [comment]
Following content is inside the idea.log-file:
`
$ sed -n '/SaveActionManager/p' idea.log                                                                                                                                                                                                                                        2019-02-04 14:15:17,916 [16885470]   INFO - re.component.SaveActionManager - [+] Start SaveActionManager#beforeAllDocumentsSaving                                                                                                                                               2019-02-04 14:15:17,916 [16885470]   INFO - re.component.SaveActionManager - Unsaved documents (0): []                                                                                                                                                                          2019-02-04 14:15:17,916 [16885470]   INFO - re.component.SaveActionManager - End SaveActionManager#beforeAllDocumentsSaving processed 0 documents                                                                                                                               2019-02-04 14:17:54,035 [17041589]   INFO - re.component.SaveActionManager - [+] Start SaveActionManager#beforeAllDocumentsSaving                                                                                                                                               2019-02-04 14:17:54,035 [17041589]   INFO - re.component.SaveActionManager - Unsaved documents (0): []                                                                                                                                                                          2019-02-04 14:17:54,035 [17041589]   INFO - re.component.SaveActionManager - End SaveActionManager#beforeAllDocumentsSaving processed 0 documents                                                                                                                               2019-02-04 14:20:21,149 [17188703]   INFO - re.component.SaveActionManager - [+] Start SaveActionManager#beforeAllDocumentsSaving                                                                                                                                               2019-02-04 14:20:21,149 [17188703]   INFO - re.component.SaveActionManager - Unsaved documents (0): []                                                                                                                                                                          2019-02-04 14:20:21,149 [17188703]   INFO - re.component.SaveActionManager - End SaveActionManager#beforeAllDocumentsSaving processed 0 documents                                                                                                                               2019-02-04 14:22:01,726 [17289280]   INFO - re.component.SaveActionManager - [+] Start SaveActionManager#beforeAllDocumentsSaving                                                                                                                                               2019-02-04 14:22:01,726 [17289280]   INFO - re.component.SaveActionManager - Unsaved documents (0): []                                                                                                                                                                          2019-02-04 14:22:01,726 [17289280]   INFO - re.component.SaveActionManager - End SaveActionManager#beforeAllDocumentsSaving processed 0 documents                                                                                                                               2019-02-04 14:23:02,250 [17349804]   INFO - re.component.SaveActionManager - [+] Start SaveActionManager#beforeAllDocumentsSaving                                                                                                                                               2019-02-04 14:23:02,250 [17349804]   INFO - re.component.SaveActionManager - Unsaved documents (0): []                                                                                                                                                                          2019-02-04 14:23:02,250 [17349804]   INFO - re.component.SaveActionManager - End SaveActionManager#beforeAllDocumentsSaving processed 0 documents                                                                                                                               2019-02-04 14:23:21,221 [17368775]   INFO - re.component.SaveActionManager - [+] Start SaveActionManager#beforeAllDocumentsSaving                                                                                                                                               2019-02-04 14:23:21,221 [17368775]   INFO - re.component.SaveActionManager - Unsaved documents (0): []                                                                                                                                                                          2019-02-04 14:23:21,221 [17368775]   INFO - re.component.SaveActionManager - End SaveActionManager#beforeAllDocumentsSaving processed 0 documents                                                                                                                               2019-02-04 14:24:26,527 [17434081]   INFO - re.component.SaveActionManager - [+] Start SaveActionManager#beforeAllDocumentsSaving                                                                                                                                               2019-02-04 14:24:26,527 [17434081]   INFO - re.component.SaveActionManager - Unsaved documents (0): []                                                                                                                                                                          2019-02-04 14:24:26,527 [17434081]   INFO - re.component.SaveActionManager - End SaveActionManager#beforeAllDocumentsSaving processed 0 documents
--
`

And i am sure that it doesnt work. When i am trying to save a file, click into another window and switch back to the IDE no changes are done.

**Comment by N3XT0R** [comment]
![image](https://user-images.githubusercontent.com/1297846/52214530-21dd5380-2892-11e9-852a-220ffe8ef37f.png)

**Comment by dubreuia** [comment]
Duplicates #222
