### ISSUE TITLE
Add save actions settings to global intellij import export settings

### ISSUE THREAD

**Issue by simonmarshall** [dubreuia/intellij-plugin-save-actions#225]
**Is your feature request related to a problem? Please describe.**
I'd like the save actions settings to be able to export to/import from a specific file.  
I appreciate it is stored under the .idea folder, but rather than asking the user to copy a file into Intellij's own project folder, I'd like the plugin to manage the process.  It's safer and future-proof.
(I think this request is different from https://github.com/dubreuia/intellij-plugin-save-actions/issues/73 and https://github.com/dubreuia/intellij-plugin-save-actions/issues/137.)

**Describe the solution you'd like**
To be able to export to/import from a save actions settings file from Settings > Other Settings > Save Actions, much like I can with code style setting (eg, Settings > Editor > Code Style > Java).

**Describe alternatives you've considered**
Telling users they can copy a file into their .idea folder and restart intellij.

**Additional context**
Thanks for the plugin!

**Comment by dubreuia** [comment]
That would be really nice, I wanted to do that for a while but I can't find the time. PR welcome

**Comment by webern** [comment]
Yeah, this would be nice. Our team needs to share settings to avoid reformatting churn and it would be nice to include the save actions settings there.

**Comment by dubreuia** [comment]
@webern YSK that this is already possible, just commit the settings file: https://github.com/dubreuia/intellij-plugin-save-actions#files-location

Still a nice feature, but already possible.

**Comment by webern** [comment]
Sadly, this is a very large enterprise with very specific ways of doing things. The .idea folder is two levels above the git repository, and we wouldn't be allowed to check stuff like this in anyway. So we've worked around that issue by sharing a zip export of the code style scheme for the project.

Anyway, long story short, maybe I can take a look at implementation. I've never touched a JetBrains plugin before but maybe I can find an example in a plugin that does export it's settings through the file->export settings pathway. For example, we use the Lombok plugin which does this.

**Comment by jdileonardo** [comment]
I'd prefer if it was stored at an IDE level, and not at a Project level.

My org uses the Settings Repository feature meaning all devs are using the same set of settings for their IDE. Having the Save actions config exported to the settings repo means we're not managing it at a per project basis.

Is this the case for others?

**Comment by mayconmfl** [comment]
Please @dubreuia, this feature it's so necessary. I'd like to share all configs export to my team.

**Comment by dubreuia** [comment]
Hello @mayconmfl, I won't have time to implement this, but you can submit a PR anytime. The contributing guide is here: https://github.com/dubreuia/intellij-plugin-save-actions/blob/master/CONTRIBUTING.md

**Comment by CodingSpiderFox** [comment]
I also want to have it as global settings and not only per project. But it should be possible to override the settings at project level

**Comment by CodingSpiderFox** [comment]
I also want to have it as global settings and not only per project. But it should be possible to override the settings at project level

**Comment by xbeta** [comment]
All the code style rules should apply globally.

**Comment by dubreuia** [comment]
Moved to ideas https://github.com/dubreuia/intellij-plugin-save-actions/projects/2

**Comment by julienmbandong** [comment]
The discussion goes in all directions and then we come to an off topic. Recalling that the starting point was: how to share the save-actions settings.

**Comment by maurogonzalezcastelli** [comment]
Hi! Is finally this feature available?

**Comment by dwilches** [comment]
Is there a workaround for this while it gets developed?

I see @dubreuia mentions you can commit `.idea/saveactions_settings.xml` but we have the .idea folder excluded as it contains more than just this file, some things are keymap configurations per user for example.

I also couldn't find that file in the `.idea` folder, so it seems in newer PyCharm's it's no longer there?

As our users already import the `settings.zip` file, it would be ideal to have the "actions on save" also configurable in there, instead of asking them to do a second step for copying the `saveactions_settings.xml` file.
