### ISSUE TITLE
Use rustfmt for Rust sources

### ISSUE THREAD

**Issue by tobia** [dubreuia/intellij-plugin-save-actions#226]
**Is your feature request related to a problem? Please describe.**

Right now IntelliJ IDEA is using an internal formatter engine for Rust code, which doesn't produce the same output as the standard `rustfmt` utility provided by Rust. This is problematic because if multiple developers working on code use *different* automatic re-formatters, this will increase formatting-related commit noise instead of getting rid of it. See [this issue](https://github.com/intellij-rust/intellij-rust/issues/1087#issuecomment-464780930) for my views on the topic.

**Describe the solution you'd like**

Right now it's unclear whether JetBrains will embrace or push `rustfmt` more. I really like having my code re-formatted on save (hence my use of this plugin), but when I'm writing Rust code I need it to be done with the `rustfmt` tool, not the IntelliJ formatter. 

It would be great if Save Actions added an option (or even just defaulted) to use `rustfmt` for Rust code, instead of the homemade IntelliJ formatter. The same should be done for other languages with a default, sanctioned formatting tool, eg. `gofmt` for Go code, etc.

**Describe alternatives you've considered**

I have raised the issue with the IntelliJ Rust plugin developers, as linked above, and I'm waiting for a reply.

**Comment by dubreuia** [comment]
Hey @tobia, can you try the next version of the plugin and tell me if it works for you? Details are in #118.

You can download this file, and add it to intellij: [Save Actions-1.4.0-RC5.zip](https://github.com/dubreuia/intellij-plugin-save-actions/files/2777071/Save.Actions-1.4.0-RC5.zip). Then, setup a "quick list" that calls `rustfmt`, then setup save actions to call that quick list on save.

**Comment by dubreuia** [comment]
Duplicates #118
