### ISSUE TITLE
"Reload files in running debugger" runs too early

### ISSUE THREAD

**Issue by kangarko** [dubreuia/intellij-plugin-save-actions#246]
**Describe the bug**
"Reload files in running debugger" option seems to be run after the files are compiled, making no effective change. I must make another change, let's say an empty line, and save it again for the changes to be reflected in the compiler.

**Video of the problem:**
In the video, you can see the changing the message for the first time takes no change in the game, I had to add an empty space and save it the second time for the change to take place.

Link: https://i.imgur.com/9Jx3ytV.gifv

**What triggered the plugin**
CTRL+S

**Versions**
IntelliJ IDEA 2019.2 EAP (Community Edition)
Build #IC-192.5281.24, built on June 19, 2019
Runtime version: 1.8.0_202-b08 amd64
VM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 4012M
Cores: 12
Registry: 
Non-Bundled Plugins: Lombook Plugin, com.dubreuia, de.santiv.fastscrolling, org.nik.presentation-assistant

**Comment by dubreuia** [comment]
Hey @kangarko thanks for the issue, it will add details to #209

**Comment by kangarko** [comment]
Do you please have an ETA on this? I am recording a course and literally have to wait 1 second and press the save again. Eclipse has Save Actions feature working flawlessly so you can take a look as an inspiration.

**Comment by dubreuia** [comment]
@kangarko I won't have time to fix this in the near future, PR are welcomed, you can follow the [contributing guide](https://github.com/dubreuia/intellij-plugin-save-actions/blob/master/CONTRIBUTING.md) for an development environment setup.

The feature will be deactivated in the next version until it is fixed because too many people complain about it (see #209).

**Comment by kangarko** [comment]
I can make a donation but I have no idea how to tamper with IntelliJ :)

Thanks for being upfront

**Comment by kangarko** [comment]
@dubreuia any fixes so far? Thats literally the only reason why I am using your plugin.

We are a community of coders for Minecraft. Restarting the entire thing takes up to 30 seconds, while using Eclipse (which has Save Actions as inbuilt feature that works fine) takes 3.

Really consider this.

**Comment by kangarko** [comment]
@dubreuia I see you are working on this plugin, has this problem been yet resolved? Just got a customer facing it, pretty sure they used the latest version

**Comment by dubreuia** [comment]
Hello @kangarko, no I'm not working on this problem, and I won't have time to look at it anytime soon. You can submit a PR anytime, the contributing guide is here: https://github.com/dubreuia/intellij-plugin-save-actions/blob/master/CONTRIBUTING.md

**Comment by JavaFactoryDev** [comment]
As it looks, this bug is not so difficult to fix. 
The reloader reloaded too early.
So you only have to delay the time when the reload is triggered or do I see it wrong?

I think I could fix this. 
It would be very nice if you could tell me the exact CodeStyle (or at least the class) that triggers the reloading because I don't feel like reading through the whole project.

Thanks to kangarko for being so dedicated to his students^^

Greetings,
Leonhard

**Comment by JavaFactoryDev** [comment]
It was really easy to fix < 30 minutes.

**Comment by dubreuia** [comment]
Hey @JavaFactoryDev, thank you for looking into this. You should probably be looking at the `BuildProcessor` class in the `com.dubreuia.processors` package.

If you have a fix ready, you can submit it as a PR at https://github.com/dubreuia/intellij-plugin-save-actions/pulls.

Cheers,

**Comment by dubreuia** [comment]
@JavaFactoryDev I've tried to add your fix, but I didn't add a "forceCompile" action, I just always force the compilation for the reload. The actions "compile" and "reload" are now mutually exclusive.

@JavaFactoryDev @kangarko can you tell me if that's what you had in mind?

**Comment by dubreuia** [comment]
Released in [1.8.0](https://github.com/dubreuia/intellij-plugin-save-actions/releases/tag/v1.8.0).
