### ISSUE TITLE
The "final"-modifier is not added to local variable in lambda block

### ISSUE THREAD

**Issue by marstran** [dubreuia/intellij-plugin-save-actions#252]
**Describe the bug**
Save Actions is adding the final-modifier to all my local variables and fields, except local variables inside a lambda block. 
I have these settings activated (related to the final modifier):
- Add final modifier to field
- Add final modifier to local variable or parameter
- Remove final from private method

This setting is deactivated:
- Add final modifier to local variable or parameter except if it is implicit

Given the following code:

    List<Integer> list = Stream.of(1, 2, 3)
            .map(i -> {
                int res = i + 1;
                return res;
            }).collect(Collectors.toList());

After triggering Save Actions, I get the following result:

    final List<Integer> list = Stream.of(1, 2, 3)
            .map(i -> {
                int res = i + 1;
                return res;
            }).collect(Collectors.toList());

I expected `int res = i + 1;` to become `final int res = i + 1;`

**What triggered the plugin**
I tried with both CTRL+SHIFT+S and CTRL+S.

**Versions**
IntelliJ IDEA 2019.2 (Ultimate Edition)
Build #IU-192.5728.98, built on July 23, 2019
Runtime version: 11.0.3+12-b304.10 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1960M
Cores: 4
Registry: git.explicit.commit.renames.prohibit.multiple.calls=false
Non-Bundled Plugins: com.dubreuia, BashSupport

Save Actions version: 1.5.0+2018.3

**Comment by dubreuia** [comment]
Hey @marstran, thank you for the bug report. This might be a bug in the inspection, if it is we should send a bug report to Jetbrains. I won't have time to check this out anytime soon. PR welcomed.

**Comment by t-kameyama** [comment]
See https://youtrack.jetbrains.com/issue/IDEA-227649

**Comment by dubreuia** [comment]
Woah @t-kameyama thanks. We'll try the fix when the next EAP is released.

PR: https://github.com/JetBrains/intellij-community/pull/1264

**Comment by dubreuia** [comment]
Closing, reopen if needed.
