### ISSUE TITLE
With Gradle, Save Action kicking off 1 build for every Java file

### ISSUE THREAD

**Issue by kurtg123** [dubreuia/intellij-plugin-save-actions#256]
I think this is a regression as I've had this problem before. 

With the Build actions "Compile Files(using "Build>Build Project") checked, it frequently kicks off several hundred builds which may correspond for each of the Java files.   Ideally, I should see only one build. 

Let me know if this doesn't ring any bells and I'll provide logs or screen shots.

**Comment by dubreuia** [comment]
Hey guys, compile and reload are buggy, I'll have to deactivate them they cause too many problems.

**Comment by dubreuia** [comment]
Duplicates #209

**Comment by kurtg123** [comment]
You can disable the "Compile files" under the Build actions.    I now
trigger is manually or when I try to run something.
