### ISSUE TITLE
Disable reformatting if file have merge conflicts

### ISSUE THREAD

**Issue by huksley** [dubreuia/intellij-plugin-save-actions#257]
**Product** 
Intellij IDEA, [x] Reformat file enabled
Git backed project

**Description**
When reformatting file with merge conflicts, i.e.

```
++<<<<<<<HEAD
code block1
++=======
code block2
++>>>>>>>develop
```

formatting becomes messed up and event merge conflict markers are moved.
With complex files and a lot of changes, this makes IDEA unusable to fix these conflicts manually.

**Ways to reproduce**
1. Make a change in one branch in the file
2. Make a change in another branch in the same file in the same place
3. Merge `git merge <another-branch>`
4. Open file to edit in IDEA
5. Make some changes and press save

**Comment by dubreuia** [comment]
Interesting, never though of that, thanks for the submission.

I won't have time to implement that anytime soon, PRs welcomed.

**Comment by dubreuia** [comment]
Moved to ideas https://github.com/dubreuia/intellij-plugin-save-actions/projects/2
