### ISSUE TITLE
Jetbrains Rider compatibility

### ISSUE THREAD

**Issue by pirons** [dubreuia/intellij-plugin-save-actions#266]
Hi,
I love the plugin in WebStorm.
Now, however, I'm also using Jetbrains Rider and I was wondering if you could add support for that browser as well?

Thanks!

**Comment by eddyekofo94** [comment]
Yes please, I would love to use it on Rider also.

**Comment by dubreuia** [comment]
Hello, I present you this 4 year old issue, #18, which tracks the advancement on the development of the plugin for each Jetbrains product.

Unfortunately, the plugin doesn't work properly in Rider without more development (I don't know what is the problem, but it seems the reformat doesn't work).

I won't have time to implement this anytime soon, but you can submit a PR anytime by following the https://github.com/dubreuia/intellij-plugin-save-actions/blob/master/CONTRIBUTING.md guide.

**Comment by dubreuia** [comment]
Duplicates #18
