### ISSUE TITLE
Save Actions Batch request fails post first successful execution

### ISSUE THREAD

**Issue by SabhtarshaMojo** [dubreuia/intellij-plugin-save-actions#268]
**Describe the bug**
Execution the save actions batch on a Java package(say p2) fails after a successful execution on another package (say p1). 
The execution again succeeds on p2 if I restart the IDE and run the batch action again but then fails on the next package.

I tried to look into the idea.log and also tried to debug through the plugin code and found that the Engine::isPsiFileFresh returns a true in the first round whereas returns false thereafter for all files in the package. Validated this by adding some logs to the plugin and the value for modificationStamp was 0 for all the files in the package.
I am not sure why this is happening as couldn't find any more information on when this modificationStamp is updated by IntelliJ and what is its significance. (tried my hands for the first time with any plugin code)

**What triggered the plugin**
Code->SaveActions->Execute on Multiple Files.

**Versions**
IntelliJ IDEA 2019.2.3 (Community Edition)
Build #IC-192.6817.14, built on September 24, 2019
Runtime version: 11.0.4+10-b304.69 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Registry: ide.windowSystem.autoShowProcessPopup=true, ide.editor.tabs.open.at.the.end=true, documentation.show.toolbar=true, debugger.watches.in.variables=false, ide.tooltip.initialDelay=839
Non-Bundled Plugins: Batch Scripts Support, CMD Support, Lombook Plugin, com.dubreuia, com.intellij.phing, com.poratu.idea.plugins.tomcat, com.thoughtworks.gauge, com.urswolfer.intellij.plugin.gerrit, net.seesharpsoft.intellij.plugins.csv, org.jetbrains.erlang, BashSupport, PythonCore, training

**Comment by dubreuia** [comment]
Hey @SabhtarshaMojo, thank you for taking the time to test the problem, I really appreciate it!

I'll try to debug myself, but I'm not sure I'll have the time soon. Can you give me more information on:

> Execution the save actions batch on a Java package(say p2) fails after a successful execution on another package (say p1).

What do you mean by "fail", do you have an exception? What is the outcome?

>  The execution again succeeds on p2 if I restart the IDE and run the batch action again but then fails on the next package.

If I understand correctly, first time you call "Execute on Multiple Files" with a package it works, second time it doesn't, maybe because "modificationStamp was 0"? 

Thinking about it, I'm pretty sure executing on multiple files (batch) should NOT test for the modification stamp. In general, the plugin should apply the actions on modified files only (checking `modificationStamp`), but during batch execution it should apply to all files, modified or not.

**Comment by SabhtarshaMojo** [comment]
Hey @dubreuia, appreciate the prompt reply. 👍 
**Answer 1:** By "fail" I mean that the files in the package are not at all updated with the expected settings. These files stay untouched. If I modify any of the file (say add a space) and trigger the `Save File` action, the rules defined in the `Save Actions plugin config` are applied to it.

**Answer 2:** Yes, I added some logs in the method Engine::isPsiFileFresh which is called from the isPsiFileEligible function.
![image](https://user-images.githubusercontent.com/27720012/66627421-4ce62700-ec19-11e9-90ce-2c675deb35d4.png)

**Below are some more findings,**
I tried doing this first thing after coming back to office, and it looks like it has nothing to do with the order of execution, (as wrongly mentioned in the bug description above) as the below happened with my first execution after starting intelliJ, I executed the `Save Actions` on Multiple files by selecting a package, and only 2 files (marked orange in the screenshot) out of all the files were processed, because the modificationStamp returned 5 for them (none of the files in this package were modified as this was a fresh clone), and all other files were not processed as the modificationStamp was 0.
When I added just a space in one of the "other" files(IAdapterConstants.java) above and triggered a `Save File`, this file was updated as per the `Save Actions` settings. Noticed my log for modificationStamp in this case said value = 3 (marked in green in screenshot 2).
**ScreenShot 1:** `Save Actions` on the package with successful execution on 2 files and no execution on "other" files.
![Screenshot 2019-10-11 at 11 25 56 AM](https://user-images.githubusercontent.com/27720012/66628525-b74c9680-ec1c-11e9-82ae-af170f3320c9.png)
**Screenshot 2:** `Save Actions` logs when the file is saved after adding a space character using the `Save File` action.
![Screenshot 2019-10-11 at 11 26 50 AM](https://user-images.githubusercontent.com/27720012/66628537-c0d5fe80-ec1c-11e9-8f04-7f059a1a422c.png)

**Comment by SabhtarshaMojo** [comment]
> Thinking about it, I'm pretty sure executing on multiple files (batch) should NOT test for the modification stamp. In general, the plugin should apply the actions on modified files only (checking `modificationStamp`), but during batch execution it should apply to all files, modified or not.

I tried changing the function as below and its now working.. not sure if this is right though..
![image](https://user-images.githubusercontent.com/27720012/66629514-99346580-ec1f-11e9-9fe5-1228903ad556.png)

**Comment by dubreuia** [comment]
>  When I added just a space in one of the "other" files(IAdapterConstants.java) above and triggered a Save File, this file was updated as per the Save Actions settings. Noticed my log for modificationStamp in this case said value = 3 (marked in green in screenshot 2).

The `modificationStamp` value is really interesting, seems like the value changes depending on the state of the file. I might be able to use this for better handling of file states. I'm going to look into it.

> I tried doing this first thing after coming back to office, and it looks like it has nothing to do with the order of execution, (as wrongly mentioned in the bug description above) as the below happened with my first execution after starting intelliJ, I executed the Save Actions on Multiple files by selecting a package, and only 2 files (marked orange in the screenshot) out of all the files were processed, because the modificationStamp returned 5 for them (none of the files in this package were modified as this was a fresh clone), and all other files were not processed as the modificationStamp was 0.
When I added just a space in one of the "other" files(IAdapterConstants.java) above and triggered a Save File, this file was updated as per the Save Actions settings. Noticed my log for modificationStamp in this case said value = 3 (marked in green in screenshot 2).

For what I understand: 5 means something like "not fresh but intellij just started" and 3 means "newly modified". Maybe the plugin, in general, should test for 3 only.

> I tried changing the function as below and its now working.. not sure if this is right though..

That is the modification I was thinking. Pretty sure that's what we want for this issue. Would you mind making a pull request if the modification works for you? I'll also test it on my end when I have time and release it in the next version.

Thanks

**Comment by dubreuia** [comment]
Fixed #272
