### ISSUE TITLE
Save Actions does not work when detekt plugin is also enabled

### ISSUE THREAD

**Issue by marco-eckstein** [dubreuia/intellij-plugin-save-actions#270]
Save Actions does not work when the [detekt plugin](https://plugins.jetbrains.com/plugin/10761-detekt) is also installed and enabled. This may be a bug in either plugin See [other plugin's issue](https://github.com/arturbosch/detekt-intellij-plugin/issues/50).

**Comment by dubreuia** [comment]
Hey @marco-eckstein, thank you for the issue. Hello @arturbosch, fellow plugin developer :D 

Like @arturbosch said, probably the detekt plugin overrides the file previously saved by the save-actions plugin. I see a `saveDocument` here https://github.com/arturbosch/detekt-intellij-plugin/blob/f840b0c58d084c78d26e7436220303a9a41094bc/src/main/kotlin/io/gitlab/arturbosch/detekt/DetektAnnotator.kt#L48. Not sure the best way to fix this.

**Comment by marco-eckstein** [comment]
No, the `autocorrect` feature is disabled. Just installing and enabling the detekt plugin is enough to break Save Actions.

**Comment by dubreuia** [comment]
Is this still an issue? If yes reopen
