### ISSUE TITLE
after update save actions settings reset

### ISSUE THREAD

**Issue by CarsarSky** [dubreuia/intellij-plugin-save-actions#276]
when i update save actions, save actions doesn't work.I need reset settings again.I use Intellij idea on MacOS.I don't know if I used it wrong.
Thank you

**Comment by dubreuia** [comment]
Hello @CarsarSky, thanks for this issue.

What version of intellij and save actions are you using?

> save actions doesn't work

What do you mean? Is there an error ? If yes, what is it? If not what is the problem?

> I need reset settings again

I'd I understand correctly, once you reset the settings it works again? What do you mean by reset the settings?

**Comment by CarsarSky** [comment]
> Hello @CarsarSky, thanks for this issue.
> 
> What version of intellij and save actions are you using?
> 
> > save actions doesn't work
> 
> What do you mean? Is there an error ? If yes, what is it? If not what is the problem?
> 
> > I need reset settings again
> 
> I'd I understand correctly, once you reset the settings it works again? What do you mean by reset the settings?

Sorry, my English is poor, it not a error. i use intellij Idea version is `2019.2.4`. i use save actions version is `1.7.0+2018.3` . Today save actions prompt me to update. when i finish update. I found that I needed to reconfigure my save actions plugin. The previous configuration disappeared.I don't think it's a error.
but i think there's some trouble with the reconfiguration.

**Comment by dubreuia** [comment]
Ok thank you for the clarifications, I can't reproduce but I'll look into it anyway.

TODO: add serialize test on storage

**Comment by CarsarSky** [comment]
Thank you very much.

**Comment by dubreuia** [comment]
Duplicates #239
