### ISSUE TITLE
Webstom 2019.3 RC - some actions missing

### ISSUE THREAD

**Issue by pronovaso** [dubreuia/intellij-plugin-save-actions#277]
**Describe the bug**
When I updated plugin and go setup it,something missing me?In Build actions?
What I want use after save the file run optimize imports,reformat with prettier and save the file(s).
Here is my settings from Webstom on Mac OS
![Snímek obrazovky 2019-11-25 v 14 09 24](https://user-images.githubusercontent.com/30770999/69543233-72db4700-0f8d-11ea-9479-aa33c612cd1f.png)
![Snímek obrazovky 2019-11-25 v 14 09 39](https://user-images.githubusercontent.com/30770999/69543234-7373dd80-0f8d-11ea-8890-7e17ef404988.png)

**Comment by dubreuia** [comment]
Hello @pronovaso, thank you for the issue. What exactly is the action you are missing? Execute quick list? Because I'm not sure I even released that. Maybe you where on a custom built? I can try adding it back, but I'm unsure it works properly.

**Comment by pronovaso** [comment]
Yes quick list execute like in screenshot in https://github.com/dubreuia/intellij-plugin-save-actions/issues/118
Because when I check reformating checkbox,this execute internal reformating in Webstom but dont Prettier reformat.

**Comment by dubreuia** [comment]
Yeah but didn't you have a custom build from #118? Because I don't think I ever release that feature. I'll add it, but I'll mark it as beta because I know it doesn't work with all actions.

**Comment by pronovaso** [comment]
In a link is all.User with nick blowsie wrote 1.3.2019 "Using RC5, For me Reformat with Prettier is working but Fix ESLint Problems is not." And from this version are his screenshots.
In this version which was a beta I think. Or is there any chance than this plugin work what I thinking? Optimizing imports and reformat with prettier ? Because this is what I expect.

**Comment by dubreuia** [comment]
Yeah so you used the custom jar from #118, which contained the "Execute editor action". I can add the functionality to next version 1.8.0 as BETA.

You need "Execute editor action" for prettier to work. If you want, you can downgrade to that version [Save Actions-1.4.0-RC5.zip](https://github.com/dubreuia/intellij-plugin-save-actions/files/2777071/Save.Actions-1.4.0-RC5.zip) while I release 1.8.0.

**Comment by pronovaso** [comment]
Your support is great and I thank you.I will wait for new version.

**Comment by pronovaso** [comment]
Please, when do you think it will be released?

**Comment by dubreuia** [comment]
This weekend @pronovaso, check #118

**Comment by dubreuia** [comment]
Fixed by #118

**Comment by dubreuia** [comment]
Released in [1.8.0](https://github.com/dubreuia/intellij-plugin-save-actions/releases/tag/v1.8.0).
