### ISSUE TITLE
Add an option to not to add final to lombok val

### ISSUE THREAD

**Issue by RealDeanZhao** [dubreuia/intellij-plugin-save-actions#278]
**Describe the solution you'd like**
Please add an option to not to add 'final' to lombok val.

**For what product**
Intellij

**Comment by dubreuia** [comment]
Hello @RealDeanZhao, thank you for your issue. What is a lombok val?

I won't have time to implement this, but you can check the [CONTRIBUTING.md guide](https://github.com/dubreuia/intellij-plugin-save-actions/blob/master/CONTRIBUTING.md) and send a PR.

**Comment by RealDeanZhao** [comment]
@dubreuia Here is the doc for lombok val: https://projectlombok.org/features/val
I will do this if have time in the future.

**Comment by dubreuia** [comment]
Released in [1.8.0](https://github.com/dubreuia/intellij-plugin-save-actions/releases/tag/v1.8.0).
