### ISSUE TITLE
flutter delete part 'xxx.d.dart';

### ISSUE THREAD

**Issue by duduodudu** [dubreuia/intellij-plugin-save-actions#280]
**Describe the bug**
when I write flutter with package json_serializable, build_runner,json_annotation,saving .dart file will delete 'part 'xxx.d.dart';',it will create `Missing "part 'xxx.g.dart';".` and xxx.g.dart will not created. 

**What triggered the plugin**
'CTRL+S' to save file.

**Versions**
v1.7.0+2018.3

what i fix:set it disabled when writing flutter.

**Comment by dubreuia** [comment]
Hello @duduodudu, I'll need more info on this. What is flutter? What is the file content? Can you post before and after save file trigger?

**Comment by duduodudu** [comment]
1.get more info about [Flutter](https://flutter.cn/) at https://flutter.cn/ ;
2.
before:
```
import 'package:json_annotation/json_annotation.dart';
part 'demo.g.dart';
class Demo {
   int age ;
}
```
after :
```
import 'package:json_annotation/json_annotation.dart';
class Demo {
   int age ;
}
```
3.My colleague said that:
`Android Studio`-> `Preferences` -> `Languages And ...` -> `Flutter` ->` Editor ` -> `Organise Import on Save`.  is the truly reason.  on Android Studio (Version 3.5.2). but i am not sure.
4.so that the bug is that the Android Studio of different Version performed different.
5.thanks!

**Comment by dubreuia** [comment]
Hey @duduodudu does the problem happen without save actions? If you disable the plugin, does the problem persist?

**Comment by duduodudu** [comment]
Finally ,i found that : if Android Studio-> Preferences -> Languages And ... -> Flutter ->Editor -> Organise Import on Save.... is the truly reason. not about the plugin. 
I am sorry to cause misunderstanding.

**Comment by dubreuia** [comment]
Ok thank you @duduodudu
