### ISSUE TITLE
Fix ESLint Problems for "Run editor action on save"

### ISSUE THREAD

**Issue by dubreuia** [dubreuia/intellij-plugin-save-actions#287]
See #118

**Comment by ozum** [comment]
To summarize this issue:

"Run editor action on save" feature of "intellij-plugin-save-actions" works for some commands such as **"Reformat with Prettier"**, but not with **"Fix ESLint Problems"** command.

**Comment by mallowigi** [comment]
Any ideas when this will be implemented?

**Comment by dubreuia** [comment]
Tentative fix in #331
