### ISSUE TITLE
File path exclusions get ignored if IntelliJ Project Files are in a different file path than the Source Code Files

### ISSUE THREAD

**Issue by pcalouche** [dubreuia/intellij-plugin-save-actions#29]
in my setup I have something like this:

IntelliJ Project Setup:
C:\Users\pcalouch\Projects\My Project (IntelliJ project files here)
C:\Users\pcalouch\Repos\My Project (index.cfm and other source code files here)

If I use .*\.cfm as a file path exclusion index.cfm is still formatted when pressing Ctrl+S.  However it works if I set me project up like this:

C:\Users\pcalouch\Projects\My Project (IntelliJ project files along with index.cfm and other source code files here)

I thinking it could be something similar that caused this issue: Nothing happens in IntelliJ 14 Ultimate #4

**Comment by dubreuia** [comment]
Thanks for the issue I'll check it out.

**Comment by bartosz-bilicki** [comment]
Hello,
any chance for the bug to be fixed?

I want to ignore my .properties files, and currently I am not able to do so.
I do not like that save actions plugins removes empty lines from my properties files (it seems, there is no option to change that). 

For details, please see http://stackoverflow.com/questions/37250475/how-to-stop-intellij-idea-from-removing-empty-lines-from-properties-files

**Comment by dubreuia** [comment]
Version 0.11 fixes it https://github.com/dubreuia/intellij-plugin-save-actions/releases/tag/v0.11

**Comment by pcalouche** [comment]
Can confirm that it is fixed in 0.11.  Thanks!
