### ISSUE TITLE
Unnecessary final modifier for try with resources.

### ISSUE THREAD

**Issue by cbertoldi** [dubreuia/intellij-plugin-save-actions#291]
**Describe the bug**
The final modifier is added for variables declared in a try with resources. This is not necessary and causes a warning during the static analysis (unnecessary modifier).
The code looks like `try (ByteArrayInputStream bais = new ByteArrayInputStream(bytes);`
and it will be automatically changed to: `try (final ByteArrayInputStream bais = new ByteArrayInputStream(bytes);`

**What triggered the plugin**
Frame deactivation (window loses focus), CTRL+SHIFT+S, CTRL+S.

**Versions**
IntelliJ IDEA 2019.3.1 (Ultimate Edition)
Build #IU-193.5662.53, built on December 18, 2019
Runtime version: 11.0.5+10-b520.17 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.2
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Registry: ide.mac.file.chooser.native=false
Non-Bundled Plugins: CheckStyle-IDEA, EclipseCodeFormatter, FindBugs-IDEA, IdeaVIM, JRebelPlugin, PMDPlugin, ccom.intellij.idea.plugin.commerce.integration, com.dubreuia

**Comment by dubreuia** [comment]
@cbertoldi You sure this doesn't work? I merged that at the beginning of the year #232. You need to activate a specific option I think

**Comment by dubreuia** [comment]
Try activating "Add final modifier to local variable or parameter except if implicit". If it doesn't work reopen

**Comment by cbertoldi** [comment]
Yes, I forgot to mention that I've tried with that option as well but the behavior is the same.
