### ISSUE TITLE
Add new option to "Add final to method paramters"

### ISSUE THREAD

**Issue by domink** [dubreuia/intellij-plugin-save-actions#293]
I would like to add missing "final" definition to method parameters (Java)
I think that it is an accepted good practice don't modify the parameters values during method execution.

Intellij

**Comment by dubreuia** [comment]
Hello @domink, this feature is already present in the plugin using the option "Add final modifier to local variable or parameter". If you need the parameter modification, you can add a new processor in `com.dubreuia.processors.java.JavaProcessor`, based on `localCanBeFinalExceptImplicit`.

I won't have time to implement this anytime soon, but PRs are welcomed. You can check the [contributing guide](https://github.com/dubreuia/intellij-plugin-save-actions/blob/master/CONTRIBUTING.md) in the README. I'm adding the "need help" tag for this purpose. Thanks

**Comment by domink** [comment]
Yes it is. Really sorry I don’t know why I was unable to see it. Sorry.

I’m reading the guides but I’m pretty new using IntelliJ and right now I don’t feel comfortable enough to contribute... but for sure I’ll try.


Thanks a lot a good work.

**Comment by dubreuia** [comment]
Moved to ideas https://github.com/dubreuia/intellij-plugin-save-actions/projects/2
