### ISSUE TITLE
Unnecessary final modifier for try with resources.

### ISSUE THREAD

**Issue by cbertoldi** [dubreuia/intellij-plugin-save-actions#294]
As agreed I am reopening this bug because I was able to reproduce it with the activated option "Add final modifier to local variable or parameter except if implicit".

Describe the bug
The final modifier is added for variables declared in a try with resources. This is not necessary and causes a warning during the static analysis (unnecessary modifier).
The code looks like try (ByteArrayInputStream bais = new ByteArrayInputStream(bytes);
and it will be automatically changed to: try (final ByteArrayInputStream bais = new ByteArrayInputStream(bytes);

What triggered the plugin
Frame deactivation (window loses focus), CTRL+SHIFT+S, CTRL+S.

Versions
IntelliJ IDEA 2019.3.1 (Ultimate Edition)
Build #IU-193.5662.53, built on December 18, 2019
Runtime version: 11.0.5+10-b520.17 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.2
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Registry: ide.mac.file.chooser.native=false
Non-Bundled Plugins: CheckStyle-IDEA, EclipseCodeFormatter, FindBugs-IDEA, IdeaVIM, JRebelPlugin, PMDPlugin, ccom.intellij.idea.plugin.commerce.integration, com.dubreuia

**Comment by dubreuia** [comment]
Previous issue #291

**Comment by dubreuia** [comment]
Ok thanks for reopening.

I won't have time to implement this anytime soon, but PRs are welcomed. You can check the contributing guide in the README. I'm adding the "need help" tag for this purpose. Thanks

**Comment by ambition-consulting** [comment]
Same goes for final on multiple exceptions getting caught:

`try{
true;
} catch (final FooException | BaException e) {
false;
}`

this final is also not needed since implicit.

I could work on a PR for this if nobody else is yet.

**Comment by 4n4n4s** [comment]
@dubreuia @ambition-consulting yes we've got the same problem.

Example:
`
try (final InputStream resourceAsStream = classLoader.getResourceAsStream(pathToFile))
 {
...
}
`

It also creates pmd issues like https://pmd.github.io/pmd/pmd_rules_java_codestyle.html#unnecessarymodifier

Any chance that this gets fixed?

**Comment by dubreuia** [comment]
Moving to ideas https://github.com/dubreuia/intellij-plugin-save-actions/projects/2
