### ISSUE TITLE
.idea/saveactions_settings.xml not automatically reloaded

### ISSUE THREAD

**Issue by dansanduleac** [dubreuia/intellij-plugin-save-actions#295]
**Describe the bug**

We have a [gradle plugin](https://github.com/palantir/gradle-baseline/blob/81ea7244e7ed7624eed50547710f52b883d3e5cc/gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineIdea.groovy#L111) that automatically configures the `.idea/saveactions_settings.xml` file when importing a project from IntelliJ.

With other files such as `.idea/externalDependencies.xml` when a change is made IntelliJ immediately picks it up and reloads the file.

However, this doesn't happen with save actions - the config pane remains unconfigured until I close the project and open it again.

We would like the settings written to `saveactions_settings.xml` to be picked up as soon as they are written to disk.

**What triggered the plugin**

n/a

**Versions**
IntelliJ IDEA 2019.3.2 (Ultimate Edition)
Build #IU-193.6015.22, built on January 14, 2020
Runtime version: 11.0.5+10-b520.30 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: G1 Young Generation, G1 Old Generation
Memory: 8192M
Cores: 12
Registry: bigger.font.in.project.view=true, ide.tooltip.initialDelay=1003, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.intellij.plugins.watcher, CheckStyle-IDEA, Error-prone plugin, Karma, Property Sorter, org.jetbrains.plugins.rest, Pythonid, R4Intellij, anton_dev_ua.PipeTableFormatter, com.chrisrm.idea.MaterialThemeUI, com.dubreuia, com.github.droibit.plugin.rxjava.postfix, com.intellij.ideolog, com.jetbrains.plugins.ini4idea, mobi.hsz.idea.gitignore, org.intellij.scala, org.jetbrains.plugins.hocon, org.jodd.idea.props, org.toml.lang, org.rust.lang, org.scalafmt.ScalaFmt, palantir-java-format, ru.artyushov

**Comment by dubreuia** [comment]
Hello @dansanduleac,

It is nice to hear you are using the plugin. I know the UI (or the plugin in general) won't reload the settings.xml, I've tried various ways of doing this, but I wasn't able to.

I'm under a lot of work right now, so I won't be able to implement this feature anytime soon. If you feel like it, you can submit a PR anytime.

Thanks,

**Comment by dubreuia** [comment]
Your gradle-baseline plugins are a really nice idea.

**Comment by dubreuia** [comment]
Released in 2.0.0 (https://plugins.jetbrains.com/plugin/7642-save-actions/update/77136 / https://github.com/dubreuia/intellij-plugin-save-actions/releases/tag/v2.0.0)
