### ISSUE TITLE
Reformat with Prettier

### ISSUE THREAD

**Issue by MoatazAbdAlmageed** [dubreuia/intellij-plugin-save-actions#296]
Kindly we need this option
https://plugins.jetbrains.com/plugin/7642-save-actions/reviews#review=26730
https://plugins.jetbrains.com/plugin/7642-save-actions/reviews#review=26731

**Comment by dubreuia** [comment]
Hello @MoatazAbdAlmageed, thank you for your interest in the plugin. Prettier is already supported using "Editor Actions" in the plugin, see #118 and check the README (https://github.com/dubreuia/intellij-plugin-save-actions#editor-actions) for information on how to set this up.

**Comment by MoatazAbdAlmageed** [comment]
Thanks, I will check it
