### ISSUE TITLE
Add deactivation by filename

### ISSUE THREAD

**Issue by dubreuia** [dubreuia/intellij-plugin-save-actions#3]
Make it possible to deactivate the save actions on certain files (by pattern, path, etc.).

**Comment by dubreuia** [comment]
Bump by #8

**Comment by stephanenicolas** [comment]
I think a list of regexp for inclusion and exlusion should be more than enough.

**Comment by dubreuia** [comment]
Added a list of exclusions in the settings window in version 0.4. The code is in master, I'll close this issue when JetBrains reviews the version. See README for more info.
