### ISSUE TITLE
PluginException at the startup. It seems nothing happens.

### ISSUE THREAD

**Issue by gianlucagerla** [dubreuia/intellij-plugin-save-actions#301]
**Describe the bug**
Once PhpStorm updated to 2020.1 EAP. 

**What triggered the plugin**
Directly at the startup

**Versions**
PhpStorm: Build #PS-201.4865.19
Save Actions 2.0.0

[saveactionslog.txt](https://github.com/dubreuia/intellij-plugin-save-actions/files/4193287/saveactionslog.txt)

**Comment by dubreuia** [comment]
Thanks @gianlucagerla

**Comment by dubreuia** [comment]
Duplicates #299

**Comment by dubreuia** [comment]
@gianlucagerla does the IDE starts anyway?

**Comment by gianlucagerla** [comment]
> @gianlucagerla does the IDE starts anyway?

Yes..!
