### ISSUE TITLE
Add save action to add private modifier to all instance fields

### ISSUE THREAD

**Issue by whut** [dubreuia/intellij-plugin-save-actions#306]
**Describe the solution you'd like**

Add save action to add **private** modifier to all instance fields. Note that SaveActions already have adding **final** modifier to all instance fields.

**For what product**

Intellij

**Comment by dubreuia** [comment]
Hello @whut! I won't have time to implement this, but you can submit a PR anytime.

**Comment by dubreuia** [comment]
Move to ideas https://github.com/dubreuia/intellij-plugin-save-actions/projects/2
