### ISSUE TITLE
File->Save All does not trigger "Save Actions"

### ISSUE THREAD

**Issue by tandr** [dubreuia/intellij-plugin-save-actions#307]
**Describe the bug**
Save Action is not triggered for "Save All" command. I use Save All all the time - mapped it to Ctrl-S (Meta-S on Mac). I am not sure if this needs to be an additional checkbox on preferences page, or having "Activate on shortcut" would be sufficient (I would say so, but others might need more flexibility)
I understand that enabling "Activate save action on save" would give me "always reformat" result, but what I really need is this action _only_ being triggered when I explicitly click/envoke "save", not when I am just switching windows and IDEA tries to save the file in between.

**Environment**
Since I don't like code to jump back and forth while I am switching windows, I have only "Activate on shortcut" enabled.
![Screen Shot 2020-03-19 at 9 03 50 PM](https://user-images.githubusercontent.com/5227075/77132482-43ad8180-6a25-11ea-86bd-81a5aab87231.png)

**What triggered the plugin**
Nothing in this case, plugin is not triggered on Save All.

**Versions**
Save Actions 2.0.0

IntelliJ IDEA 2019.3.3 (Ultimate Edition)
Build #IU-193.6494.35, built on February 10, 2020
Licensed to XXX
Subscription is active until November 1, 2020
Runtime version: 11.0.5+10-b520.38 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.3
GC: ParNew, ConcurrentMarkSweep
Memory: 3987M
Cores: 16
Registry: 
Non-Bundled Plugins: com.intellij.plugins.watcher, com.dubreuia, io.protostuff.protostuff-jetbrains-plugin, org.jetbrains.plugins.go-template, org.jetbrains.plugins.go

**Note**
If IDEA does not allow to distinguish about how "save" was initiated - by deactivating window or by explicit user action, then feel free to close this item.

**Comment by tandr** [comment]
This might be related to #305 too

**Comment by dubreuia** [comment]
Hello @tandr! Thank you for your interest in the plugin.

When you use "Activate save actions on shortcut", you need to bind the save-actions shortcut. To do this, go to "File > Keymaps > Main menu > Code > Save Actions", find the "Execute Save Actions on shortcut" and bind it to whatever you like ("CTRL - S" for example).

**Comment by dubreuia** [comment]
I'm closing this, please reopen it if you can't make it work. Thanks

**Comment by tandr** [comment]
Thanks @dubreuia . So, if I have ctrl-s is bound to Save All, will rebinding it to "Save Action" make it no longer saving all files? 
I thought (for some reason) that your code attaches a handler to "save single file", but not "save all"...

**Comment by dubreuia** [comment]
@tandr I honestly don't know. If you test this can you report back with your findings?

>  I thought (for some reason) that your code attaches a handler to "save single file", but not "save all"...

It is actually the opposite, I can't make it work with the "save single file" event, this is also with the IdeaVim plugin is not fully supported (see https://github.com/dubreuia/intellij-plugin-save-actions#other-plugin-compatibility)
