### ISSUE TITLE
Add settings to split actions for source code and test

### ISSUE THREAD

**Issue by baseballlover723** [dubreuia/intellij-plugin-save-actions#308]
**Describe the solution you'd like**
Hi, I have been using save actions with my team, and its been a great help to us. However, one thing that we would love to have would to be able to set different settings for different parts of our project.

For us, we have flags such as `Add final modifier to field` and `Add final modifier to local variable or parameter except if it is implicit`, which is great for our production code. However, for our test code we'd like to be much more lenient and not enforce these flags, while still being able to use other parts of save actions in our test code, like automatically reformatting and optimizing imports.

It would be great if save actions could read a configuration file our test directory or if there were some other way to set multiple profiles or something, to allow for multiple configurations of save actions inside of a project.

**For what product**

Intellij

**Comment by dubreuia** [comment]
Hello @baseballlover723, thank you for your interest in the plugin. This is a big feature, I won't have time to implement this at all. You can send a PR anytime, but please consult me before starting the development so we can discuss the implementation first. Thanks!

**Comment by dubreuia** [comment]
Moving to ideas https://github.com/dubreuia/intellij-plugin-save-actions/projects/2
