### ISSUE TITLE
Plugin is incompatible with version 2020.1 of Intellij IDEA

### ISSUE THREAD

**Issue by vladislav-naydenov** [dubreuia/intellij-plugin-save-actions#313]
The plugin is incompatible with the new version of idea. When I open the IDE I'm getting error:

Plugin Error: Plugin "Save Actions Reborn" is incompatible (until build 193.SNAPSHOT < IC-201.6668.121)

**Versions**
IntelliJ IDEA 2020.1 (Community Edition)
Build #IC-201.6668.121, built on April 8, 2020
Runtime version: 11.0.6+8-b765.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 3.10.0-957.12.2.el7.x86_64
GC: ParNew, ConcurrentMarkSweep
Memory: 961M
Cores: 2
Registry: debugger.watches.in.variables=false
Non-Bundled Plugins: EclipseCodeFormatter, org.sonarlint.idea, com.wix.eslint, BashSupport
Current Desktop: Undefined

**Comment by dubreuia** [comment]
Hello @vladislav-naydenov! This is the repository for the "Save Actions" plugin, you are using "Save Actions Reborn" plugin, a fork of this plugin. You can contact the plugin authors at: https://plugins.jetbrains.com/plugin/13331-save-actions-reborn

The original "Save Actions" plugins works in 2020.1 btw ;-)
