### ISSUE TITLE
Add "Load Maven Changes" trigger

### ISSUE THREAD

**Issue by rafaelrenanpacheco** [dubreuia/intellij-plugin-save-actions#314]
Hi there!

Version 2012.1 of IntelliJ IDEA dropped a featured called "Automatically import maven dependencies". This features allowed us to edit the `pom.xml` and IntelliJ would automatically import the new dependencies and refresh it's local cache.

For some reason the thought that this is bad and dropped it, even tho they claim to be:

> Every aspect of IntelliJ IDEA has been designed to maximize developer productivity

Dropping an automatic feature in order to forces us to use the mouse and target a small popup button isn't much productive.

Would be possible for this plugin to trigger the new `Load Maven Changes` when saving the `pom.xml` file?

Thanks.

**Comment by dubreuia** [comment]
Hello @rafaelrenanpacheco, thank you for your interest in the plugin. Are you sure there isn't a "auto reload" changes for Maven? There is one for Gradle, I don't see why there wouldn't be any for Maven. 

I've searched for the `Load Maven Changes` action and couldn't find it, can you send me a screenshot of where the button / action is? We can already trigger some stuff from the plugin, please check the quick lists action: https://github.com/dubreuia/intellij-plugin-save-actions#editor-actions

**Comment by rafaelrenanpacheco** [comment]
Hello @dubreuia!

The `Load Maven Changes` is just a popup the pops when you change the `pom.xml`. For maven they removed the auto import feature for the 2020 version, and this issue is being discussed here: https://intellij-support.jetbrains.com/hc/en-us/community/posts/360007057999-importing-maven-project-automatically-on-2020-1-EAP

Just [today](https://youtrack.jetbrains.com/issue/IDEA-235459) a JB member said there's a pool to revert their changes and get back the auto import feature. Maybe in 3 years we will get back the auto import feature again.

Since there's a possibility for this in the long feature to become standard again, there's no need for this plugin to do the same.

Thanks!
