### ISSUE TITLE
Do not add final to lombok @Builder field

### ISSUE THREAD

**Issue by abrudin** [dubreuia/intellij-plugin-save-actions#315]
**Describe the bug**
When overriding fields in a lombok builder, save actions adds the final modifier although it is actually modified by invisible lombok code inside the builder. An example would be:
```
@Value
@Builder
public class TestData {
  private final Optional<String> test;

  public static final class TestDataBuilder {
    private **final** Optional<String> test = Optional.empty();
  }
}
```
where the **final** (without the **) is added by the save actions, although it does not compile because the field is modified in a lombok generated setter.

**What triggered the plugin**
CTRL+S

**Versions**
(Version 2.0.0 of Save actions, latest Intellij)

IntelliJ IDEA 2020.1 (Ultimate Edition)
Build #IU-201.6668.121, built on April 8, 2020
Runtime version: 11.0.6+8-b765.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-96-lowlatency
GC: ParNew, ConcurrentMarkSweep
Memory: 1927M
Cores: 8
Non-Bundled Plugins: Lombook Plugin, com.dubreuia, org.jetbrains.plugins.hocon, com.jetbrains.ChooseRuntime, google-java-format, mobi.hsz.idea.gitignore, org.intellij.plugins.hcl, org.jetbrains.plugins.go, Pythonid, org.jetbrains.kotlin, org.intellij.scala, com.intellij.plugins.html.instantEditing
Current Desktop: ubuntu:GNOME

**Comment by dubreuia** [comment]
Hello @abrudin, thank you for your interest in the plugin. This is a difficult issue to fix, since it requires detecting if the Lombook Plugin is active, and don't use the action at that specific place if it's the case.

I won't have time to implement this but you can submit a PR anytime. Please see the https://github.com/dubreuia/intellij-plugin-save-actions/#contributing guide.

**Comment by dubreuia** [comment]
Moved to ideas https://github.com/dubreuia/intellij-plugin-save-actions/projects/2
