### ISSUE TITLE
Do not add final for local param

### ISSUE THREAD

**Issue by liutiejun** [dubreuia/intellij-plugin-save-actions#316]
**Describe the bug**

add final for code i:
for (final int i = 0; i < jsonArray.size(); i++) {

**What triggered the plugin**
Frame deactivation (window loses focus), CTRL+SHIFT+S, CTRL+S, etc.

save action version: 2.0.0

**Versions**
In Intellij, go to "Help > About > Copy" and paste it here

IntelliJ IDEA 2019.3.3 (Ultimate Edition)
Build #IU-193.6494.35, built on February 11, 2020

Subscription is active until April 7, 2021
Runtime version: 11.0.5+10-b520.38 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6
GC: ParNew, ConcurrentMarkSweep
Memory: 990M
Cores: 4
Registry: 
Non-Bundled Plugins: AliP3CPlugin, Lombook Plugin, MavenRunHelper, com.dubreuia

**Comment by dubreuia** [comment]
Hello @liutiejun, thank you for your interest in the plugin. I won't have time to implement this but you can submit a PR anytime. Please see the https://github.com/dubreuia/intellij-plugin-save-actions/#contributing guide.

**Comment by dubreuia** [comment]
Moved to ideas https://github.com/dubreuia/intellij-plugin-save-actions/projects/2
