### ISSUE TITLE
Ctrs+S doesn't trigger format action.

### ISSUE THREAD

**Issue by devcppdtis** [dubreuia/intellij-plugin-save-actions#317]
**Describe the bug**
Ctrs+S doesn't fire format action.

**What triggered the plugin**
CTRL+S doesn't trigger format code on the edited file.

From log:
2020-04-24 13:16:12,683 [8194120]   INFO - re.component.SaveActionManager - [+] Start SaveActionManager#beforeAllDocumentsSaving 
2020-04-24 13:16:12,683 [8194120]   INFO - re.component.SaveActionManager - Locating psi files for 0 documents: [] 
2020-04-24 13:16:12,683 [8194120]   INFO - re.component.SaveActionManager - End SaveActionManager#beforeAllDocumentsSaving 

**Versions**
IntelliJ IDEA 2020.1 (Ultimate Edition)
Build #IU-201.6668.121, built on April 8, 2020
Runtime version: 11.0.6+8-b765.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 990M
Cores: 4
Non-Bundled Plugins: GrepConsole, Lombook Plugin, com.dubreuia, com.intellij.ideolog, com.tabnine.TabNine

**Comment by bayangan1991** [comment]
Experiencing the same issue in PyCharm since the 2020.1 update

**Comment by dubreuia** [comment]
Hello @devcppdtis and @bayangan1991. I don't have enough information to help you. I just tested this in Intellij IDEA 2020.1 Ultimate and pressing CTRL+S does trigger the save-actions. Maybe you have a specific keybinding for saving? It does show in the log that the plugin triggers though.

**Comment by dubreuia** [comment]
Please note that the save actions plugin is bound to the "Save All Documents" only (please verify your shortcuts). See #222 on this subject.

Also, a recent issue might be linked #318. You can probably change your keybindings as a workaround.

**Comment by dubreuia** [comment]
I'm closing this, please reopen if you need more help.

**Comment by devcppdtis** [comment]
[idea.log](https://github.com/dubreuia/intellij-plugin-save-actions/files/4677994/idea.log)
