### ISSUE TITLE
Not working in IntelliJ 2020.1.1

### ISSUE THREAD

**Issue by AlexLnz** [dubreuia/intellij-plugin-save-actions#318]
**Describe the bug**
The functions are no more working on IntelliJ2020.1.1 (Win 64).
For example reformat code at save does not work.
For example optimize imports at save does not work.

**What triggered the plugin**
--

**Versions**
IntelliJ IDEA 2020.1.1 (Ultimate Edition)
Build #IU-201.7223.91, built on April 30, 2020
Licensed to -------------------
Subscription is active until December 10, 2020
Runtime version: 11.0.6+8-b765.40 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry: terminal.escape.moves.focus.to.editor=false
Non-Bundled Plugins: Statistic, Lombook Plugin, com.dubreuia, org.sonarlint.idea

**Comment by AlexLnz** [comment]
Can be fixed by re-mapping the hotkey for the "Save All" action.
Changed from Shift-Ctrl-S to Ctrl-S and it works now.

**Comment by dubreuia** [comment]
Hi @AlexLnz, glad you figured this out. Similar to #317.
