### ISSUE TITLE
Regenerate and replace serialVersionUID

### ISSUE THREAD

**Issue by onlyonce** [dubreuia/intellij-plugin-save-actions#319]
**Describe the solution you'd like**
Regenerate and replace serialVersionUID if it's different than JDK generate it.

**For what product**
Intellij

**Comment by dubreuia** [comment]
Hello @onlyonce, thank you for your interest in the plugin. I won't have time to implement this, but you can submit a PR anytime. Thanks!

**Comment by dubreuia** [comment]
Moved to ideas https://github.com/dubreuia/intellij-plugin-save-actions/projects/2
