### ISSUE TITLE
Adds @VisibleForTesting annotation for methods only used in tests.

### ISSUE THREAD

**Issue by zhanghaze** [dubreuia/intellij-plugin-save-actions#323]
**Describe the solution you'd like**

As a save action for class, it check all fields/methods that are only used in tests source and add @VisibleForTesting annotation to it.

**For what product**

Intellij, java.

**Comment by dubreuia** [comment]
Hello @zhanghaze, thank you for your interest in the plugin (sorry I missed this issue during triage). I won't have time to implement this, but you can submit a PR anytime, see contributing guide in the README. Cheers

**Comment by dubreuia** [comment]
Moved to ideas https://github.com/dubreuia/intellij-plugin-save-actions/projects/2
