### ISSUE TITLE
Limit save action/inclusion, only the currently open and active file?

### ISSUE THREAD

**Issue by MostHated** [dubreuia/intellij-plugin-save-actions#326]
Hey there,
   I created a small tool that I added as an external tool in which I pass in the arguments: ```-p $ContentRoot$ -f $FileNameWithoutExtension$ -y``` and I added it to the Quick List and wanted to use the "trigger on hotkey" (ctrl + shift + s) but I am not sure how to make the Save Action only apply this to the currently open file so that it can populate the external tools parameters with the correct $FileNameWithoutExtension$. Is there a way I can go about doing this?

Either:
```
Android Studio 4.0
Build #AI-193.6911.18.40.6514223, built on May 20, 2020
Runtime version: 1.8.0_242-release-1644-b01 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 3959M
Cores: 32
```
or
```
IntelliJ IDEA 2020.2 EAP (Ultimate Edition)
Build #IU-202.5792.28, built on June 17, 2020
IntelliJ IDEA EAP User
Expiration date: July 17, 2020
Runtime version: 11.0.7+10-b944.12 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 3959M
Cores: 32
```

**Comment by dubreuia** [comment]
Hello @MostHated, thank you for your interest in the plugin. I'm pretty sure you could use the "Editor Actions" feature for this, as it triggers per file (for now?). Can you follow https://github.com/dubreuia/intellij-plugin-save-actions#editor-actions and report back if you can make it work? Thanks

**Comment by dubreuia** [comment]
See #118 and #310 (funnily enough, we have the opposite problem here).

**Comment by dubreuia** [comment]
Moved to ideas https://github.com/dubreuia/intellij-plugin-save-actions/projects/2
