### ISSUE TITLE
 Using mybatis to map the file XML will not be automatically formatted 

### ISSUE THREAD

**Issue by shoreu** [dubreuia/intellij-plugin-save-actions#329]
![图片](https://user-images.githubusercontent.com/57432535/87925731-48f20a00-cab3-11ea-84cd-111379286ba0.png)
This is my configuration，
Is there any incorrect configuration?
![图片](https://user-images.githubusercontent.com/57432535/87925971-9e2e1b80-cab3-11ea-936e-2c0ace8752f2.png)
This is the directory where the mybatis file is located

**Comment by dubreuia** [comment]
Hello, this should work. Can you do the following actions and send your idea.log file (check [files locations](https://github.com/dubreuia/intellij-plugin-save-actions#files-location)):

- Modify the xml file
- Trigger the save-actions by changing window or shortcut (probably CTRL + SHIFT + S)

**Comment by dubreuia** [comment]
Reopen with more info
