### ISSUE TITLE
"Save Actions Reborn" is incompatible (until build 201.SNAPSHOT < IU-202.6948.69)

### ISSUE THREAD

**Issue by plum117** [dubreuia/intellij-plugin-save-actions#333]
For one week or two now I always have this error in Intellij for this plugin:

> Plugin "Save Actions Reborn" is incompatible (until build 201.SNAPSHOT < IU-202.6948.69)

Will this really be fixed by a new Intellij version? Or something is required in the plugin itself?

Thanks

Save Action Reborn version: 1.6.1

Intellij version:
IntelliJ IDEA 2020.2.1 (Ultimate Edition)
Build #IU-202.6948.69, built on August 24, 2020
Licensed to
You have a perpetual fallback license for this version
Subscription is active until July 30, 2021
Runtime version: 11.0.8+10-b944.31 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Non-Bundled Plugins: Key Promoter X, Builder Generator, CheckStyle-IDEA, EclipseCodeFormatter, String Manipulation, net.sjrx.intellij.plugins.systemdunitfiles, org.intellij.plugins.hcl, org.jetbrains.plugins.hocon, com.intellij.kubernetes, org.jetbrains.kotlin, org.intellij.scala, training

**Comment by dubreuia** [comment]
Hello @plum117, this is the GitHub issue for the "Save Actions" plugin, not the "Save Actions Reborn" plugin. Please open an issue on their Github (https://github.com/KotlinFactory/intellij-plugin-save-actions)

Or switch to "Save Actions" :)

**Comment by plum117** [comment]
Oh sorry, I had both pages opened on each project,  I choose the wrong page. Actually, if the reborn version does not get a fix soon, I might surely change :D

**Comment by dubreuia** [comment]
FYI "Save Actions Reborn" last update is "Sep 23, 2019", and "Save Actions" is "Feb 1, 2020" and I'm preparing a new release soon :)

**Comment by plum117** [comment]
Actually, it is the link in the project of the reborn that is wrong, the link "https://github.com/KotlinFactory/intellij-plugin-save-actions#issues" below contains another link pointing to "https://github.com/dubreuia/intellij-plugin-save-actions/issues"

Oh juste read your last... then I will switch :D
