### ISSUE TITLE
Propagate Static everywhere

### ISSUE THREAD

**Issue by Arthur-Milchior** [dubreuia/intellij-plugin-save-actions#339]
**Describe the solution you'd like**
I'm trying to apply your product to a whole project. And it is asking, again and again, to which methods I want to propagate Static. I would appreciate:
* a button "select all" to select all methods
* a button "All methods" to apply "select all" to every files, so that I don't have to accept so many time.

**For what product**

Android-studio

Thanks for your product !

**Comment by dubreuia** [comment]
Hey @Arthur-Milchior, thank you for your interest in the plugin. However, this plugin doesn't do what you think it does, it is only calling IDE actions when the file is saved. What you are trying to do is applying IDE for all your files, this is outside the scope of the plugin. I also don't know what is "Propagate Static everywhere", is it "Add class qualifier to static member access"?

There is a "batch mode" in the plugin that might help you, see https://github.com/dubreuia/intellij-plugin-save-actions#activation, "Activate save actions on batch".
