### ISSUE TITLE
Support feature not change exists import order

### ISSUE THREAD

**Issue by wulinjie122** [dubreuia/intellij-plugin-save-actions#345]
**Describe the solution you'd like**
When press Ctrl + S , the plugin optimized import statement and removed unused import, but it also changed the order of exists import statement.

**For what product**
Hope don't change exists import order.

Intellij IDEA

**Comment by wulinjie122** [comment]
because **change order** will raise a lot of Git diffs.

**Comment by dubreuia** [comment]
Hello @wulinjie122, thank you for your interest in the plugin. The save-actions plugin doesn't sorts or cleans the imports, it only calls the IDE to do so. If you want the imports not to be sorted, you should configure the IDE likewise (in code style, imports, sort order or something). Let me know if you need anything else. Cheers
