### ISSUE TITLE
Request: allow to set the options be the default for all projects, and not just the current one

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [dubreuia/intellij-plugin-save-actions#346]
**Describe the solution you'd like**
Please offer to set it for all projects:
![image](https://user-images.githubusercontent.com/5357526/100354916-89313e00-2ff9-11eb-8329-c5e7f038340b.png)

**For what product**
Android Studio.

**Comment by dubreuia** [comment]
Hello @AndroidDeveloperLB, this is a long standing issue, we need to support both by and global configuration. PRs welcomed for this, but please we need to discuss the implementation before starting. Please use the main issue #305 for discussing this.
