### ISSUE TITLE
Request: for each option in the settings, show preview of an example of what it handles

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [dubreuia/intellij-plugin-save-actions#347]
**Describe the solution you'd like**
Some sort of "before" and "after". Maybe like the preview of code formatting.
It can either be via a tooltip, or a part of the UI that changes as you hover over each of them (or when you press on "?" button).
I'm talking about this:

![image](https://user-images.githubusercontent.com/5357526/100355219-0b216700-2ffa-11eb-9d5f-59543dd36ae2.png)

**For what product**
Android Studio.

**Comment by dubreuia** [comment]
@AndroidDeveloperLB I would love to add that and I've though about this many times. I'm keeping this for later, I probably will never have time to implement, but we never know, and again PRs welcomed. Cheers

**Comment by dubreuia** [comment]
Request: a save-actions.io website

**Comment by AndroidDeveloperLB** [comment]
@dubreuia I'm very confused. Why you say you like it, and say you close it? And why you say you close it, and you don't close it?
And what is this website? I can't even access it...

**Comment by dubreuia** [comment]
>@dubreuia I'm very confused. Why you say you like it, and say you close it? And why you say you close it, and you don't close it? And what is this website? I can't even access it...

Sorry about the confusion, this issue stays open. I'd also like to make a website, but I haven't bought the domain yet (I'm just making a note to myself).

**Comment by AndroidDeveloperLB** [comment]
@dubreuia Oh ok.

**Comment by dubreuia** [comment]
Will not do, PRs welcomed

**Comment by AndroidDeveloperLB** [comment]
@dubreuia I'm not sure I follow. You say you are not against, but still close it?
:(
