### ISSUE TITLE
Request: Skip formatting based on filetype

### ISSUE THREAD

**Issue by uweschaefer** [dubreuia/intellij-plugin-save-actions#348]
**Problem:**

When saving a markdown file, it is formatted (in a way that breaks the content). I love you plugin for java files, xml etc, but for markdown i wish, i could skip formatting altogether.

**Consequence**

i can either stop using your fine plugin (not an option for me personally), or strictly use another editor for files that should not be formatted, which is pretty hard to remember.

**Suggested Solution:**

Keep an editable white(or black)-list of file types (*.java,*.xml) to format on save. If too much trouble in terms of UI, define a format-exclusions.xml or something that this list is read from, if the filename in configured in the UI.

thanks,

btw: i love your plugin!

**Comment by dubreuia** [comment]
Hey @uweschaefer, thank you for your interest in the plugin. Please see [file inclusions / exclusions](https://github.com/dubreuia/intellij-plugin-save-actions#file) in the documentation and let me know if it fits your needs (I think adding an exclusion regex of `.+\.md` should do the trick). Reopen if you need anything else. Cheers.

**Comment by uweschaefer** [comment]
duh. stupid me! Sorry & Thanks!
