### ISSUE TITLE
Request: add some way to apply the "save actions" to all files, everywhere in the project

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [dubreuia/intellij-plugin-save-actions#349]
**Describe the solution you'd like**
I know it triggers each time you save, but maybe as a start, it could be nice to apply the changes to all files.
If this is already possible, please let me know.

**For what product**
Android Studio.

**Comment by dubreuia** [comment]
Hello @AndroidDeveloperLB, thank you for your continued interest in the plugin. Yes, you can use "batch mode" for that:

1. Activate batch mode: https://github.com/dubreuia/intellij-plugin-save-actions#activation
2. Then use the following action: "Code > Save Actions > Execute on multiple files" and following the scope dialog

**Comment by AndroidDeveloperLB** [comment]
@dubreuia Oh cool. Thank you!
