### ISSUE TITLE
Custom settings based on file type

### ISSUE THREAD

**Issue by sebkur** [dubreuia/intellij-plugin-save-actions#350]
I've seen #348 and understand that I can disable formatting for file types completely based on their extension or path. 
What I'm looking for would be an option to enable / disable certain formatting actions based on the file type. I think it is not possible yet, is it?

To give you an idea, why I need this: I'm using Android Studio and need "Rearrange fileds and methods" to be enabled for XML files, because canonical element attribute order is very desirable there. However I do not want to rearrange Java source files, because this messes up the (non-normalized) order of fields we use in our project. I know I can navigate to the `Arrangement` tab in `Editor` → `Code Style` → `Java` and minimize the arrangement applied to Java files, however it seems impossible to disable rearrangment there completely.

**Comment by dubreuia** [comment]
@sebkur Thank you for your interest in the plugin, sorry it took me so long to answer. This is a great idea for a feature, but this is also hard to implement. The save-actions engine can support that, but the UI will be hard to make.

I'm accepting PRs if you want to implement it, please see the CONTRIBUTE.md file in the repo. Cheers

**Comment by dubreuia** [comment]
Move to https://github.com/dubreuia/intellij-plugin-save-actions/projects/2 (ideas)
