### ISSUE TITLE
Flip operands of equals method

### ISSUE THREAD

**Issue by rw00** [dubreuia/intellij-plugin-save-actions#354]
Given code similar to the following:/0
```
public static final String CONST = "...";
...
String k = ...;
if (k.equals(CONST)) {
 ...
}
```
Then there should be an option to automatically flip the operands of the equals method. After save, the code should look like:

```
if (CONST.equals(k)) {

}
```

The downside of this is that it might hide NPEs.

This should be doable in IntelliJ because there's already a runnable action for it.

**Comment by dubreuia** [comment]
Hello @rw00 :wave:, thank you for opening this. This is a great idea, but I won't have time to implement this. But I'm accepting PRs, a adding an (existing) quick fix is really easy, if you want to look at it.

**Comment by dubreuia** [comment]
Move to https://github.com/dubreuia/intellij-plugin-save-actions/projects/2 (ideas)
