### ISSUE TITLE
Enable headless automation for CI verification

### ISSUE THREAD

**Issue by ambition-consulting** [dubreuia/intellij-plugin-save-actions#356]
In our team, we have very strict rules on what can get merged and what not. Having your save actions executable in headless mode would allow us to verify automatically whether it has been execute before starting the pull request.

Using a docker container, this could be triggered: https://github.com/ccaominh/intellij-inspect

Intellij

**Comment by dubreuia** [comment]
Hello @ambition-consulting , thank you for your interest in the plugin. I'm unfamiliar with what you call "headless mode". If what you mean is packaging save-actions alone without Intellij, it can't work. The plugin doesn't actually do anything, it just calls stuff in Intellij at the right time. 

I think what you are looking for is a linter, like checkstyle for example, that can be run from Gradle.

Closing for now
