### ISSUE TITLE
Problem with scala imports

### ISSUE THREAD

**Issue by janxbar** [dubreuia/intellij-plugin-save-actions#36]
Hi,

thank you for excellent plugin, as former Eclipse user I like it. However I have strange problems with my scala code. Auto save is configured to only organize imports, all other configurations are switched off. When I modify one line and I switch focus away from IntelliJ, the organize imports deletes some of imported class and the file cannot be compiled. This is quite unfortunate. I tried to do Code | Optimize imports manually but it works fine. Just when this action is called from the plugin it doesn't work as expected. Seems like there is some problem with interaction with scala plugin?

Intellij 2016.1.1, Scala plugin 3.0.2 and Save Actions plugin 0.7.

**Comment by dubreuia** [comment]
I didn't tried the plugin with every language, so it might not work with some. I'll check it out.

**Comment by dubreuia** [comment]
Coded scala with the scala plugin recently, this issue is still present
