### ISSUE TITLE
reformat(save action ) is different from reformat(ctrl+alt+L)

### ISSUE THREAD

**Issue by 562498146** [dubreuia/intellij-plugin-save-actions#361]
environment :
          system:  window10
          idea:       intellij  idea 2020.3
          plugin:   save actions 2.2.0

question:   Save Action triggers formatting files in a different format than Ctrl + Alt +L formatting files

**Comment by 562498146** [comment]
![image](https://user-images.githubusercontent.com/25143495/106438941-1b4e3a80-64b2-11eb-9175-b400210f85b3.png)

**Comment by 562498146** [comment]
![image](https://user-images.githubusercontent.com/25143495/106439773-09b96280-64b3-11eb-92db-6afc93d074e5.png)
ctrl+s triggers formatting files

**Comment by 562498146** [comment]
![image](https://user-images.githubusercontent.com/25143495/106439863-248bd700-64b3-11eb-951c-a89aff466d8b.png)

**Comment by dubreuia** [comment]
Hello @562498146 , those are 2 different actions. What is expected?
