### ISSUE TITLE
Do not call synchronous repository update in EDT

### ISSUE THREAD

**Issue by francescortiz** [dubreuia/intellij-plugin-save-actions#362]
**Describe the bug**

After a few minutes using PyCharm I get `Do not call synchronous repository update in EDT`. Disabling the plugin stops the error from happening.

**What triggered the plugin**

It just happens.

**Versions**
PyCharm 2020.3.3 (Professional Edition)
Build #PY-203.7148.72, built on January 27, 2021

**Comment by dubreuia** [comment]
Cannot reproduce, reopen if still present

**Comment by dubreuia** [comment]
Thanks for opening @francescortiz :pray:
