### ISSUE TITLE
Line break in the middle of a string value

### ISSUE THREAD

**Issue by lcsqlpete** [dubreuia/intellij-plugin-save-actions#369]
I am running into situations where a hard line break is inserted part way through a string value in an html file which results in a string of spaces being appended to the first part of the string if I get its value using javascript.

For example:

```
<span id="exchange-dates" data-fromdateymd="{{ExchangeFromDateYMD}}" data-todateymd="{{ExchangeToDateYMD}}">{{ExchangeFromDateMDY}}
- {{ExchangeToDateMDY}}</span>
```

It may not be obvious because of the github formatting but there is a line break after "{{ExchangeFromDateMDY}}"

I should have mentioned a couple of things.  First, the <span> tag above was all on one line before the file was saved and second, this does not happen if I disable the File Save plugin

**Comment by ktomk** [comment]
@lcsqlpete does it happen when you disable save-actions and only reformat the code?

**Comment by lcsqlpete** [comment]
Good point. Reformatting did produce the same problem so I guess this is a PHPStorm problem not the plugin.

**Comment by ktomk** [comment]
Then I'd say you can close the issue here @lcsqlpete - and for the concrete problem: you might be able to control this with line-length settings for html files in the PhpStorm editor settings.

**Comment by lcsqlpete** [comment]
Not a Save File plugin problem
