### ISSUE TITLE
Not working properly in Android Studio 2.0 (Intellij Idea 15 based) when used with Eclipse Code Formatter

### ISSUE THREAD

**Issue by Propheta13** [dubreuia/intellij-plugin-save-actions#37]
What is not working (checked):
- Code reformatting;
- Adding final to field access.

Both for version 0.7. Reformatting working OK for the same situation with version 0.4.

**Comment by dubreuia** [comment]
There are some regressions in 0.7 due to modifications in editor focus, I'll check it out.

**Comment by existme** [comment]
Also, the plugin is not listed when I click on browse repositories in Android Studio 2 though it is available in IntelliJ.

**Comment by dubreuia** [comment]
Duplicate #18
