### ISSUE TITLE
Add option to make project in save actions.

### ISSUE THREAD

**Issue by Dimes** [dubreuia/intellij-plugin-save-actions#38]
Just installed the save actions plugin and love it. One improvement that could be added is to add the option to make the project on save. IntelliJ currently has this option, but the option only performs a make if there is no code running. This makes hot swapping very annoying because you must manually press Cmd+F9 to make the project after each change. It would be great if save actions could also make the package after every save, regardless if code is running or not.

**Comment by dubreuia** [comment]
It's already on the roadmap I just don't have time to work on it. There's @sbmpost that sent me code to do it so I created #33 (I modified the subject it didn't mention compilation). 

I'm closing this one but subscribe to #33
