### ISSUE TITLE
Add a mode that enables Save Actions for all projects

### ISSUE THREAD

**Issue by jimshowalter** [dubreuia/intellij-plugin-save-actions#397]
We love Save Actions, but find it a bit tedious to have to enable it on a per-project basis.

It would be great if we could check some box that makes it apply to every project.

**Comment by ZengAtHere** [comment]
i have same demand

**Comment by fishermans** [comment]
The common approach on this request is to configure your default projects settings for new projects. Once you have have done this, new projects will have Save Actions enabled by default. To do so, go to File -> New project setup -> Preferences for new projects and setup your settings.

**Comment by jimshowalter** [comment]
Wasn't aware of that option, and it works perfectly. Thank you!
