### ISSUE TITLE
Add final to method parameters

### ISSUE THREAD

**Issue by macwirbel** [dubreuia/intellij-plugin-save-actions#41]
Thanks for updating the save actions to 0.9. One thing is still annoying and not what I expected updating code that had been written with eclipse.
The option "Add final to local variable" I would like to check, because I want the final added to:
`String text = object.getName();`
(Otherwise checkstyle will complain.)
But I do not need the final added to all parameters of all method declarations.
Gives many superflous code changes. Please do not include that in this option.
Perfectly all right would be a separate option "Add final to method parameters" which I could uncheck if desired.

**Comment by dubreuia** [comment]
That would be a nice enhancement, I'll try to add that. Thanks

**Comment by bskidan** [comment]
I wanted request the same thing. A separate "Add final to method parameters" would be great.

**Comment by madorb** [comment]
I'll third this request! would love to have that as a separate option!

**Comment by nusmanov** [comment]
Hi,
could you tell us, if the feature "Add final to method parameters" is planned to be implemented?

ps: Thanks for this very helpful plugin.

**Comment by dubreuia** [comment]
No it is not planned but you can submit a PR anytime. Everything you need to know to setup your environment is there: https://github.com/dubreuia/intellij-plugin-save-actions#development-environment

**Comment by dubreuia** [comment]
Moved to https://github.com/dubreuia/intellij-plugin-save-actions/projects/2
