### ISSUE TITLE
java.lang.RuntimeException: Cannot invoke (class=SaveActionManager, method=beforeAllDocumentsSaving, topic=FileDocumentManagerListener)

### ISSUE THREAD

**Issue by dietl-conrad** [dubreuia/intellij-plugin-save-actions#438]
**Describe the bug**
When I want to save file changes the plugin crashes and all changes are gone.

[stacktrace.txt](https://github.com/dubreuia/intellij-plugin-save-actions/files/13174130/stacktrace.txt)

**What triggered the bug
CTRL+S

**Versions**
IntelliJ IDEA 2023.2.4 (Ultimate Edition)
Build #IU-232.10203.10, built on October 24, 2023
Runtime version: 17.0.8.1+7-b1000.32 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.15.0-87-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 3990M
Cores: 8
Registry:
    editor.minimap.enabled=true

Non-Bundled Plugins:
    org.intellij.plugins.hcl (232.8660.88)
    org.jetbrains.plugins.go-template (232.9921.89)
    com.intellij.ideolog (222.1.0.0)
    com.intellij.properties.bundle.editor (232.8660.88)
    com.intellij.kubernetes (232.10203.2)
    com.dubreuia (2.3.0)
    io.codearte.props2yaml (1.0.2)
    org.intellij.tasks.navigation (0.5.1)
    com.jetbrains.packagesearch.intellij-plugin (232.9921.28)
    org.sonarlint.idea (9.1.0.75538)

Kotlin: 232-1.9.0-IJ10203.10
Current Desktop: ubuntu:GNOME

**Comment by fishermans** [comment]
Please close and see: #431
