### ISSUE TITLE
Remove unused SuppressWarnings annotations is removing annotations that it shouldn't

### ISSUE THREAD

**Issue by roy-porter-itv** [dubreuia/intellij-plugin-save-actions#45]
Latest version of the plugin is removing @SuppressWarnings for Sonar issues, when it shouldn't.

**Comment by greenkiwi** [comment]
I've noticed the same thing with it removing java warnings.  For example it removes this warning:
```
@SuppressWarnings("unchecked") final List<NobOwner> list = criteria.list();
```
When it is an unchecked cast.

**Comment by dubreuia** [comment]
I haven't touch that for a while, I'm wondering if it might be an Intellij problem. Didn't find anything in YouTrack though.

**Comment by greenkiwi** [comment]
I'll poke around.  I wonder whether or not some setting isn't set correctly, that results in the warnings not being viewed as "required"

**Comment by timovandeput** [comment]
I observe the same for both `@SuppressWarnings` and for `//noinspection` annotations.

**Comment by dubreuia** [comment]
WNF
