### ISSUE TITLE
Unexpected file exclusions

### ISSUE THREAD

**Issue by pcalouche** [dubreuia/intellij-plugin-save-actions#48]
I have two different machines each running the same IntelliJ (2016.1.2 built May 14th) and version 0.11 of the plugin.  

On one machine everything works great.  On the other I have no exclusions although I used to have some and have since removed all of them. On this machine nothing gets formatted.  The IntelliJ log always shows something similar to this for each file:

C:/Users/pcalouch/Projects/TheraDoc_4.7.0/theraDocWeb/web/theradoc/app/components/features/aur/ar-details.component.html excluded in [] 

I have tried un-installing and re-installing the plugin with no luck on that machine.  Could the plugin somehow be referencing some out of date exclusion?  The debug doesn't tell what exclusion preventing the file from being formatted.  

Any ideas?  Thanks!

**Comment by dubreuia** [comment]
The log prints an empty set of exclusion [], which should not exclude anything.

Could you post the plugin settings file? It should be located at `~/.IntelliJIdea2016.1/config/options/saveactions_settings.xml`. You can try deleting the file (or renaming it to "saveactions_settings.xml.old") so it resets the default plugin values.

**Comment by pcalouche** [comment]
Removing the file you mentioned and letting it get re-created fixed the problem.  I captured the contents of the saveactions_settings.xml that was bad and compared it to the newly created one.  It looks like an exclusion was in there, but I didn't see it listed in the Save Actions settings UI.  Maybe it will help you determined what happened.  Either way thank you for your quick response.  Love the plugin.

[saveactions_settings.zip](https://github.com/dubreuia/intellij-plugin-save-actions/files/287426/saveactions_settings.zip)

**Comment by dubreuia** [comment]
Happy to hear it corrected the problem, I'll check out the issue.

**Comment by dubreuia** [comment]
WNF
