### ISSUE TITLE
Trailing spaces ain't stripped out

### ISSUE THREAD

**Issue by stephanenicolas** [dubreuia/intellij-plugin-save-actions#5]
When using the plugin, I lost the ability to remove trailing spaces on save (setting in Preference >> Editor >> Trailing Spaces).

**Comment by dubreuia** [comment]
You mean it overrides the value set in "Strip trailing space on Save" ? Two cases I see where this could be a problem:

- "Strip trailing space on Save = None" and the plugin is activated (modified lines or all lines), it will always remove the trailing spaces
- "Strip trailing space on Save = Modified Lines" and the plugin is activated (all lines), it will remove the trailing spaces even on non-modified lines

**Comment by dubreuia** [comment]
will not fix
