### ISSUE TITLE
Breaking gradle plugin

### ISSUE THREAD

**Issue by MALPI** [dubreuia/intellij-plugin-save-actions#51]
When opening and editing a gradle file with the save actions plugin activated, the "organize imports" task is running after each hit of a key.

**Comment by dubreuia** [comment]
This is a known issue see #14. As a workaround, please use file exclusions (https://github.com/dubreuia/intellij-plugin-save-actions#file-path-exclusions)

The following should exclude all gradle files (root and nested).

    .*/.*\.gradle
    .*\.gradle

**Comment by MALPI** [comment]
Thanks a lot, exclusion works. Surprisingly this issue appears first time since the last update to Intellij IDEA 2016.1.3.

**Comment by markiewb** [comment]
FYI the same issue occurs when you have the XText/XTend plugin installed

**Comment by dubreuia** [comment]
Yeah, some plugin seems to change the frequency of document write.

I was thinking maybe I could try to check event source like in this PR #46 and maybe filter anything that doesn't come from Intellij.
