### ISSUE TITLE
Make configuration "per project"

### ISSUE THREAD

**Issue by Toilal** [dubreuia/intellij-plugin-save-actions#58]
Configuration of the plugin seems to be saved globally.

I have some projects that needs save actions to be enabled, and some others that doesn't. Currently, when I disable save actions in one project, it also disable it in the other.

Would it be possible to save the plugin configuration inside the project instead ?

**Comment by dubreuia** [comment]
This is an old issue I don't have time to implement but would really like to do. Please check https://github.com/dubreuia/intellij-plugin-save-actions/issues/10
