### ISSUE TITLE
Support save actions in PyCharm

### ISSUE THREAD

**Issue by NorthIsUp** [dubreuia/intellij-plugin-save-actions#6]
The plugin does not seem to work in PyCharm (no File > Save Options > etc. menu exists).

**Comment by dubreuia** [comment]
Yes indeed, I'm not currently supporting PyCharm (or any other variation than Intellij IDEA) so it shouldn't show up in the plugin repository in PyCharm. Did you install it from there ?

That being said, I should support it, so I'm marking that as an enhancement.

**Comment by mkasu** [comment]
I'd also be interested in support for CLion, if possible :)

**Comment by dubreuia** [comment]
No worries, it helps knowing what feature is of interest. I'll do #18 next.

**Comment by maggu2810** [comment]
You have removed the 0.6 milestone from #18

Any news to get this plugin working in PyCharm?
Do you need more testers?

**Comment by dubreuia** [comment]
@maggu2810 I'm just not using milestone anymore that is why I removed it.

I got a pull request (https://github.com/dubreuia/intellij-plugin-save-actions/pull/22/commits) that should enable the plugin in PyCharm too, I just need to test it.

**Comment by dubreuia** [comment]
Duplicates #18 this is the next thing I implement.
