### ISSUE TITLE
Resolve conflicts hangs after git pull (organize imports)

### ISSUE THREAD

**Issue by mihu86** [dubreuia/intellij-plugin-save-actions#62]
IDEA 2016.2.5, win7 64bit
Save actions 0.12 / Organize imports turned on

If I do a git pull with auto stash, when I click on the "Merge" button on the resolve dialog the merge panel appears but immediately after this there comes a progress popup with "Organize imports". But this organize imports never finishes, the cancel button on the popup does nothing, only closing the IDEA process from the task manager helps.
After restarting IDEA, clicking on Git -> Resolve conflicts... works as intended, I can merge the files.

**Comment by dubreuia** [comment]
OK I'll check it out, thanks.
