### ISSUE TITLE
Add a manual save option where plugin is not trigerred

### ISSUE THREAD

**Issue by Kaerol** [dubreuia/intellij-plugin-save-actions#63]
Please add a feature:

Run plugin after manual save (or shortcut).

Now, it save file every few seconds and make mess when coding e.g. when stop typing it reorganise code.

**Comment by dubreuia** [comment]
The plugin doesn't work properly if you have other plugins that mess with the normal save cycle in intellij. For example if you have the SonarLint Plugin, it will try to save often to analyse the code, and that save will make the SaveActions plugin reformat the file (while you're typing). Some languages (scala...) will trigger save too often too.

Two options 

- add an option to SaveActions to trigger only on CTRL-S and not on automatic save
- support SaveActions with other plugins by checking the save event source

**Comment by Kaerol** [comment]
or 
- SaveActions execute when editor loses focus
- SaveActions execute after some [   ] seconds after last keypress.

**Comment by dubreuia** [comment]
From #54

Comment: I would love to be able to save without save actions. ctrl-s (save with action) ctrl-alt-s (save without action) becouse sometimes it better not to.

From the comment section in : https://plugins.jetbrains.com/plugin/7642

**Comment by dubreuia** [comment]
Somewhat similar to #59

**Comment by dubreuia** [comment]
Released v0.23

**Comment by dubreuia** [comment]
Please consider rating this plugin if you are using it: https://plugins.jetbrains.com/plugin/7642-save-actions
