### ISSUE TITLE
WebStorm Support

### ISSUE THREAD

**Issue by DQvsRA** [dubreuia/intellij-plugin-save-actions#69]
Hi
Good and very useful idea for plugin.
So, it possible to install plugin for WebStrom but there is no "Other Settings" in IDE.
How can i use it for WebStorm IDE?

**Comment by dubreuia** [comment]
I never tested it in WebStorm (one reason is that I don't have a license) but I'll try to check it out when I have time.

**Comment by markiewb** [comment]
Perhaps you can asl JB to get a free OSS license of Webstorm

https://www.jetbrains.com/buy/opensource/

Den 1 feb. 2017 15:48 skrev "Alexandre DuBreuil" <notifications@github.com>:

**Comment by krasa** [comment]
You could probably use EAP for now https://confluence.jetbrains.com/display/WI/WebStorm+EAP

**Comment by markiewb** [comment]
Duplicate of #18

**Comment by dubreuia** [comment]
Thanks for the EAP and OSS license tips guys

**Comment by dubreuia** [comment]
Duplicates #18
