### ISSUE TITLE
Add custom formatter selection

### ISSUE THREAD

**Issue by meonlol** [dubreuia/intellij-plugin-save-actions#72]
We would like to select the google-java-format plugin as default formatter as save-action.

This could be implemented as a selection drop-down or, since I see you inherit from IntelliJ's Formatter directly, by providing a way to execute custom macros.

**Comment by dubreuia** [comment]
There is already a similar request #61, but I'm really not sure I want to step outside what is provided in "Settings > Editor > Code Style > Java > Scheme > Your scheme", which is the formatting style the save-actions plugin will use.

If I can easily retrieve the available formaters and put them in a drop down that might work. Custom macros have also been asked before, but this is lots of work.

**Comment by markiewb** [comment]
I would not invest time for this, until the google-java-format plugin is compatible to 2016.3+. Google has to fix it first. 

https://github.com/google/google-java-format/issues/115

**Comment by letientai299** [comment]
So now, Google have fixed their issue. How about this issue?

I have installed both plugins in IntelliJ IDEA 2017.2 EAP. And Save Actions still use default formatter. I still have to trigger Google Formatter manually (via `Ctrl-Alt-L`)

**Comment by dubreuia** [comment]
Duplicates #118
