### ISSUE TITLE
Project Specific Settings Stored Outside .idea folder

### ISSUE THREAD

**Issue by Veeramanikandan1493** [dubreuia/intellij-plugin-save-actions#73]
We have been using Intellij 14 on Ubuntu 16.04. 
Project inherits default settings of the plugin from Intellij. 
But **saveactions_settings.xml** file being saved on  **/home/userName** location instead of **.idea** folder of project as mentioned at [https://github.com/dubreuia/intellij-plugin-save-actions](url)

**Comment by dubreuia** [comment]
I'm pretty sure they changed the way the settings files are saved around Intellij 15, and I'm using that new storage API. I'm actually surprised it works in 14...

I can check if I can retrofit the functionality to an old Intellij but I'm not sure that's possible.

**Comment by dubreuia** [comment]
WNF
