### ISSUE TITLE
Do not invoke save actions if there are compile errors

### ISSUE THREAD

**Issue by markiewb** [dubreuia/intellij-plugin-save-actions#76]
As described in https://github.com/dubreuia/intellij-plugin-save-actions/issues/75#issuecomment-292832115 the formatter-on-save could mess up the code while there are still compile errors, because the user has not finished typing.

**Comment by dubreuia** [comment]
I'm testing this one before releasing, this is really useful. We could make it default = true I think.

Thanks for the PR, I'm releasing 0.15 with it today
