### ISSUE TITLE
Execute save actions only when working in regular editor

### ISSUE THREAD

**Issue by sftwrengnr** [dubreuia/intellij-plugin-save-actions#82]
First: Thanks for building and maintaining this plug-in!

I think, the save actions should not be executed when code got changed & saved via a diff viewer. I know this behavior from Eclipse and actually miss it a lot. When editing via a diff viewer I want only to change exactly that spot I am working on, nothing else. This behavior, of course, could be made configurable.

Thanks a lot.

**Comment by dubreuia** [comment]
OK I'll look into that. I'm not using the Intellij diff viewer so I never thought about that use case.
