### ISSUE TITLE
Support inspections

### ISSUE THREAD

**Issue by krasa** [dubreuia/intellij-plugin-save-actions#9]
It would be nice if you could check inspections that would run and quick fix everything in changed files.

From comments to Eclipse Code Formatter plugin: 
"I need Intellij to add the 'final' modifier everywhere possible. similar to Eclipse's: "Use modifier 'final' where possible" under "Save Actions"."

**Comment by dubreuia** [comment]
That would be a nice feature. I'm marking that as enhancement. Thanks for the idea, I'll keep you posted.

**Comment by dorongold** [comment]
+1. 
That would be the last thing missing for convincing everybody in my team to switch from eclipse to intellij.

**Comment by krasa** [comment]
I tried to call some methods and it seems to work quite well...  
```
		ApplicationManager.getApplication().invokeLater(new Runnable() {

			@Override
			public void run() {
				new WriteCommandAction.Simple(project) {

					@Override
					protected void run() throws Throwable {
						InspectionManager inspectionManager = InspectionManager.getInstance(project);
						PsiDocumentManager psiDocumentManager = PsiDocumentManager.getInstance(project);
						Document document = psiDocumentManager.getDocument(psiFile);
						psiDocumentManager.commitDocument(document);

						GlobalInspectionContext context = inspectionManager.createNewGlobalContext(false);
						LocalCanBeFinal tool = new LocalCanBeFinal();
						InspectionToolWrapper toolWrapper = new LocalInspectionToolWrapper(tool);
						List<ProblemDescriptor> problemDescriptors = InspectionEngine.runInspectionOnFile(psiFile,
								toolWrapper, context);
						for (ProblemDescriptor problemDescriptor : problemDescriptors) {
							QuickFix[] fixes = problemDescriptor.getFixes();
							if (fixes != null) {
								for (QuickFix fix : fixes) {
									if (fix != null) {
										fix.applyFix(project, problemDescriptor);
									}
								}
							}
						}

						psiDocumentManager.commitDocument(document);
					}
				}.execute();
			}
		})
```

**Comment by dubreuia** [comment]
Very nice @krasa, I'll try your code ASAP.

The best way to configure that would be to duplicate the "Settings > Editor > Inspections" option table in the save actions options, to enable / disable specific inspections on save... Then reuse your code by looping on the activated inspections and applying them.

**Comment by krasa** [comment]
Yep, that would be ideal.

**Comment by sbusse** [comment]
+1 for this enhancement. but applying quick fixes after inspections should be opt-in in settings for various reasons.

**Comment by dubreuia** [comment]
I'm currently implementing that one. I'm doing a simple version with only some inspections, so if you want to vote for the one you want, go ahead (there are so many !).

**Comment by dubreuia** [comment]
Some inspection IDs I find useful:

- localCanBeFinal
- explicitTypeCanBeDiamond
- unqualifiedFieldAccess
- suppressAnnotation
- finalPrivateMethod
- unnecessarySemicolon
- fieldCanBeFinal

**Comment by jaapcoomans** [comment]
+1
I really miss the "Use 'this' qualifier for field/method access" from Eclipse Save Actions! So I'd vote for:
* unqualifiedFieldAccess
* unqualifiedMethodAccess

**Comment by dubreuia** [comment]
Added in 0.5. Open another issue if you want more inspections, I'll add them incrementally.
