### ISSUE TITLE
[Build action] Add inspect code on save

### ISSUE THREAD

**Issue by marmistrz** [dubreuia/intellij-plugin-save-actions#90]

**Comment by dubreuia** [comment]
Yes I'd like to add this one too, but if it is like "compile", it is a bit hard to do correctly.

**Comment by marmistrz** [comment]
Where does the problem lie?

**Comment by dubreuia** [comment]
I have a loop "build -> save -> build", I need to filter events

**Comment by dubreuia** [comment]
@tflecht I don't think you can prevent save in intellij

**Comment by tflecht** [comment]
Ty for answering. :)

**Comment by dubreuia** [comment]
@tflecht I'm trying to fix another issue and I stumbled on an API that might do it: com.intellij.openapi.fileEditor.FileDocumentSynchronizationVetoer. I'll create a separate issue for this

**Comment by tflecht** [comment]
Tyvm!!

**Comment by dubreuia** [comment]
Will be fixed with #118, reopen if not enough

**Comment by dubreuia** [comment]
See #208
