### ISSUE TITLE
[Java inspection] Add quick fix make method static

### ISSUE THREAD

**Issue by NikolayMetchev** [dubreuia/intellij-plugin-save-actions#91]
There is an inspection called "Method may be static". I would like the save actions to automatically action that inspection. (This has the potential to propagate through several methods)

**Comment by dubreuia** [comment]
Sure! Could you do a PR for it? Really easy, same as a13f080cd631f7e0677af32082b1dec5e1d46cf0 you just have to find your inspection.

**Comment by rw00** [comment]
Hi @dubreuia  , 
Do you allow submitting fixes for 2 issues in one PR? (this and #135)

Thanks,

**Comment by dubreuia** [comment]
@rw00 I'd prefer two different PR, but if they don't merge (which is probably the case) you can do both issues in the same PR.

Thanks for contributing!

**Comment by dubreuia** [comment]
Hey @rw00 can you give me an example of how this works (before / after)

**Comment by dubreuia** [comment]
Fixed https://github.com/dubreuia/intellij-plugin-save-actions/releases/tag/v1.0.0
