### ISSUE TITLE
Add support for Rider

### ISSUE THREAD

**Issue by realworld666** [dubreuia/intellij-plugin-save-actions#93]
Plugin doesn't seem to work in JetBrains Rider IDE

**Comment by dubreuia** [comment]
I didn't event know that existed. Can you please test the zip in #18 issue? It should work in all products (unzip, then import jar in Rider).

If it does, post back here and I'll activate it for Rider in the plugin repository.

**Comment by realworld666** [comment]
It works so far as the settings are available in the settings menu but saving the file doesn't appear to perform any of the actions unless I'm doing something wrong

**Comment by dubreuia** [comment]
No it probably doesn't work, I'll have to debug it myself.

**Comment by MartinX3** [comment]
I can confirm @realworld666 seen behavior with the 0.17.zip.

**Comment by dubreuia** [comment]
Duplicated #18
