### ISSUE TITLE
Narrow down Java inspections to modified code

### ISSUE THREAD

**Issue by balbusm** [dubreuia/intellij-plugin-save-actions#97]
I noticed that Java inspections are not changed code sensitive.
I would be great if "Reformat only changed code" affected also Java inspections (ex. "Add final to local variable/field" would add final keyword to modified code, not entire file)
This is useful in situations when I do small change and I don't want to add final to all eligible places, but only to my newly added code.
Could you make Java inspections scope depended?

**Comment by dubreuia** [comment]
Duplicates #35
